### ISSUE TITLE
client:compile fails with "Error parsing reflection configuration"

### ISSUE THREAD

**Issue by bgmf** [gluonhq/client-maven-plugin#107]
Hi Gluon-Team

I tried to compile a simple test application (which contains Kotlin, JavaFX base, controls & graphic). 
I can compile and run it with the `javafx:run` goal, but `client:compile` fails with the following message:

```
daniel@ghua-xps15:~/git/other/packagetest$ GRAALVM_HOME=/home/daniel/programs/java/graalvm/graalvm-ce; JAVA_HOME=/home/daniel/programs/java/graalvm/graalvm-ce ./mvnw client:compile
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< ch.cnlab.jfx.test:package-test >-------------------
[INFO] Building package-test 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:compile (default-cli) @ package-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/daniel/git/other/packagetest/src/main/resources
[INFO] Nothing to compile - all classes are up to date
We will now compile your code for x86_64-linux-linux. This may take some time.
Build on Server(pid: 13044, port: 34253)
[ch.cnlab.jfx.test.appkt:13044]    classlist:   3,199.41 ms
[ch.cnlab.jfx.test.appkt:13044]        (cap):     544.55 ms
[ch.cnlab.jfx.test.appkt:13044]        setup:     636.88 ms
Error: Error parsing reflection configuration in /home/daniel/git/other/packagetest/target/client/x86_64-linux/gvm/reflectionconfig-x86_64-linux.json:
Method com.sun.javafx.logging.PrintLogger.createInstance() not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Compilation failed with result = 1
Compilation failed. See error printed above.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.540 s
[INFO] Finished at: 2020-01-15T16:19:50+01:00
[INFO] ------------------------------------------------------------------------
```

Here's my `pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.cnlab.jfx.test</groupId>
    <artifactId>package-test</artifactId>
    <version>0.0.1</version>

    <name>package-test</name>
    <description>JavaFX application to test packaging with.</description>

    <url>https://www.cnlab.ch</url>

    <scm>
        <connection>scm:git:git@git.cnlab.ch:dzimmermann/jfx-package-test.git</connection>
    </scm>

    <organization>
        <name>cnlab Software AG</name>
        <url>https://www.cnlab.ch</url>
    </organization>

    <licenses>
        <license>
            <name>Proprietary</name>
            <url>https://www.cnlab.ch</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>dzimmermann</id>
            <name>Daniel Zimmermann</name>
            <email>daniel.zimmermann@cnlab.ch</email>
        </developer>
    </developers>

    <repositories>
        <repository>
            <id>maven</id>
            <url>http://repo1.maven.org/maven2</url>
        </repository>

        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
    </repositories>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.basedir>${basedir}</main.basedir>

        <use.java.version>11</use.java.version>
        <javafx.version>11.0.2</javafx.version>
        <kotlin.version>1.3.61</kotlin.version>
        <!-- current Kotlin version does not support 13 as a target -->
        <kotlin.jvm.target>11</kotlin.jvm.target>

        <java.version>${use.java.version}</java.version>
        <maven.compile.java.version>${use.java.version}</maven.compile.java.version>
        <maven.compiler.source>${use.java.version}</maven.compiler.source>
        <maven.compiler.target>${use.java.version}</maven.compiler.target>

        <jackson.version>2.9.9</jackson.version>

        <javafx.plugin.version>0.0.3</javafx.plugin.version>
        <client.plugin.version>0.1.11</client.plugin.version>

        <app.main.class>ch.cnlab.jfx.test.AppKt</app.main.class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
            <classifier>modular</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains</groupId>
                    <artifactId>annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk7</artifactId>
            <version>${kotlin.version}</version>
            <classifier>modular</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
            <classifier>modular</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib-jdk7</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>${kotlin.version}</version>
            <classifier>modular</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
            <version>${jackson.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-reflect</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <pluginRepositories>
        <pluginRepository>
            <id>gluon-releases</id>
            <url>http://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.1.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>2.5.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>2.8.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.0.0</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>${use.java.version}</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <inherited>true</inherited>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                            <addClasspath>true</addClasspath>
                        </manifest>
                        <manifestEntries>
                            <!-- custom entries -->
                            <Specification-Vendor>${project.organization.name}</Specification-Vendor>
                            <Specification-Version>${project.version}</Specification-Version>
                            <Specification-Title>${project.name}</Specification-Title>
                            <Implementation-Vendor>${project.organization.name}</Implementation-Vendor>
                            <Implementation-Version>${project.version}-${buildNumber}</Implementation-Version>
                            <Implementation-Title>${project.name}</Implementation-Title>
                            <!-- <Automatic-Module-Name>${project.groupId}.${project.artifactId}</Automatic-Module-Name> -->
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>kotlin-maven-plugin</artifactId>
                <groupId>org.jetbrains.kotlin</groupId>
                <version>${kotlin.version}</version>
                <configuration>
                    <!-- <compilerPlugins><plugin>spring</plugin></compilerPlugins> -->
                    <!-- Supported versions: 1.6, 1.8, 9, 10, 11, 12 -->
                    <jvmTarget>${kotlin.jvm.target}</jvmTarget>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/test/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <!-- <dependency><groupId>org.jetbrains.kotlin</groupId><artifactId>kotlin-maven-allopen</artifactId><version>${kotlin.version}</version></dependency> -->
                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>${javafx.plugin.version}</version>
                <configuration>
                    <!-- javafx:compile options -->
                    <source>${use.java.version}</source>
                    <target>${use.java.version}</target>
                    <release>${use.java.version}</release>
                    <mainClass>${app.main.class}</mainClass><!-- packagetest -->
                    <!-- javafx:jlink options -->
                    <jlinkImageName>${project.artifactId}</jlinkImageName>
                    <launcher>${project.artifactId}-launcher</launcher>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>${client.plugin.version}</version>
                <configuration>
                    <!-- Uncomment to run on iOS: -->
                    <!-- <target>ios</target> -->
                    <mainClass>${app.main.class}</mainClass>
                    <graalvmHome>/home/daniel/programs/java/graalvm/graalvm-ce</graalvmHome>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${app.main.class}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

Since the source contains a `module-info.java` I'm able to not just `jlink` it, but also create a package with the `jpackager` - only this final little piece called `GraalVM` is missing.

Any idea, what could cause the reflection problem? Or is it possible to pass the suggested parameter to the `compile` goal (`-H:+AllowIncompleteClasspath`, ...)?

Thank you in advance! :smiley: 
Daniel

**Comment by jperedadnr** [comment]
You are running with JavaFX 11.0.2, and that version didn't include the `PrintLogger`. Can you try a newer version (12, 13, even 14-ea+7)?

**Comment by mipastgt** [comment]
Maybe one should update the documentation at https://docs.gluonhq.com/client/ then which says "The Gluon Client plugin leverages GraalVM, OpenJDK and JavaFX 11+" :-)

**Comment by bgmf** [comment]
@jperedadnr thanks for the reply and sorry for the delay. I was to busy today to check this issue and actually try it. But as @mipastgt said, it wasn't obvious for me from the documentation... 😄

**Comment by bgmf** [comment]
OK. For some reason I couldn't find `13.0.2` on the Maven repo (see [here](https://mvnrepository.com/artifact/org.openjfx/javafx-base)), although [Maven Central Search](https://search.maven.org/artifact/org.openjfx/javafx-base/13.0.2/jar) list it... But OK, whatever.

I could now successfully call `client:compile`! Great!

Unfortunately it fails in the following `client:link` step, but this time I think I "only" need to install a couple of dependencies. Can you verify that?

```
[INFO] --- client-maven-plugin:0.1.11:link (default-cli) @ package-test ---
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Package gtk+-3.0 was not found in the pkg-config search path.
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Perhaps you should add the directory containing `gtk+-3.0.pc'
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] to the PKG_CONFIG_PATH environment variable
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] No package 'gtk+-3.0' found
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Package gthread-2.0 was not found in the pkg-config search path.
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Perhaps you should add the directory containing `gthread-2.0.pc'
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] to the PKG_CONFIG_PATH environment variable
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] No package 'gthread-2.0' found
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Package xtst was not found in the pkg-config search path.
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] Perhaps you should add the directory containing `xtst.pc'
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] to the PKG_CONFIG_PATH environment variable
[Fr. Jan. 17 09:20:15 MEZ 2020][INFORMATION] [SUB] No package 'xtst' found
Not a dir
started linking
done linking
Linking failed. Details from linking below:
Command was: gcc /home/daniel/git/other/packagetest/target/client/x86_64-linux/gvm/package-test/launcher.o /home/daniel/git/other/packagetest/target/client/x86_64-linux/gvm/tmp/SVM-1579248985153/ch.cnlab.jfx.test.appkt.o -Wl,-Bstatic -ljava -lnio -lzip -lnet -lprefs -ljvm -lstrictmath -lj2pkcs11 -lsunec -lextnet -llibchelper -Wl,-Bdynamic -lz -ldl -lstdc++ -lpthread -rdynamic -Wl,--whole-archive -lprism_es2 -lglass -lglassgtk3 -ljavafx_font -ljavafx_font_freetype -ljavafx_font_pango -ljavafx_iio -Wl,--no-whole-archive -lGL -lX11 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lfreetype -lpangoft2-1.0 -lgthread-2.0 -lstdc++ -lz -lXtst -o /home/daniel/git/other/packagetest/target/client/x86_64-linux/package-test -L/home/daniel/programs/java/graalvm/graalvm-ce/lib/svm/clibraries/linux-amd64 -L/home/daniel/programs/java/graalvm/graalvm-ce/lib -L/home/daniel/.gluon/substrate/javafxStaticSdk/14-ea+gvm4/linux-x86_64/sdk/lib -L/home/daniel/git/other/packagetest/target/client/x86_64-linux/gvm/lib -Wl,--whole-archive -Wl,--no-whole-archive
/usr/bin/ld: -lGL kann nicht gefunden werden
/usr/bin/ld: -lgtk-3 kann nicht gefunden werden
/usr/bin/ld: -lgdk-3 kann nicht gefunden werden
/usr/bin/ld: -lpangocairo-1.0 kann nicht gefunden werden
/usr/bin/ld: -lpango-1.0 kann nicht gefunden werden
/usr/bin/ld: -latk-1.0 kann nicht gefunden werden
/usr/bin/ld: -lcairo-gobject kann nicht gefunden werden
/usr/bin/ld: -lcairo kann nicht gefunden werden
/usr/bin/ld: -lgdk_pixbuf-2.0 kann nicht gefunden werden
/usr/bin/ld: -lgio-2.0 kann nicht gefunden werden
/usr/bin/ld: -lgobject-2.0 kann nicht gefunden werden
/usr/bin/ld: -lglib-2.0 kann nicht gefunden werden
/usr/bin/ld: -lfreetype kann nicht gefunden werden
/usr/bin/ld: -lpangoft2-1.0 kann nicht gefunden werden
/usr/bin/ld: -lgthread-2.0 kann nicht gefunden werden
/usr/bin/ld: -lXtst kann nicht gefunden werden
collect2: error: ld returned 1 exit status
java.lang.RuntimeException: Linking failed
...
```

**Comment by bgmf** [comment]
That was easier then anticipated. Added the missing dev-lib for GTK and all its dependencies and linking was done in no time.

Tried to `client:run` it:
```
[INFO] --- client-maven-plugin:0.1.11:run (default-cli) @ package-test ---
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class ch.cnlab.jfx.test.FXApp
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.ja[1;a3:44m7I9N)FO
        ]a tc1omm-.-o-r-a--c-l-e-.-s-v-m-.-c-o-r-e-.-p-o-s-i--x-.-t-h-r-e-a-d-.-P-o-s--i-x-J-a-v-a-T-h-r-e-a-d-s-.-p-t-h-r-e-a-d-S-t-a-r-t-R--o-u-t--i-n-e-Pmo
sixJavaThreads.j[av[:11;9334)mI
NFCOa[sme]d  [1y;:3 2jmBaUvIaL.Dl aSnUgC.CNESoSSmc
hMeth[[d1;E3x4mcIeNFpOtmo] n[ 1cmh-.-c-n-l-a-b-.-j--f-x-.-t-e--s-t-.-F-X-A-p-p-.--<-i-n-i-t->--(-)-
--      -a-t- -j-a-v-a-.-l-a--n-g-.--C-l--a-s-s-.-g-e-t-C-o-n-s-t-r-u-c-t-o[0m(
DynamicHub.java:3349)
        at java.lang.Class.getConstructor(DynamicHub.ja[v:2[115;13)4
m       IaNtF Oc[mm.]s uTno.tjaalv atfixm.ea:p p l1i.c0a4t7i osn
.LauncherImpl.lambda$launchApplication1$8(LauncherIm[p.[j1a;v3a:48m0I1N)F
O[amt]  cFoimn.issuhned. jaatv:a 2f0x20.-a01p-p17lTi09c:a45t:i5o7n+.0P1l:0a0t
formIm[p[.1l;a3m4bmdIaN$FrOu[mA]n W[a1imt-$-1-2-(-P-l-a-t-f-o-r-m-I-m-p-l-.-j-a-v-a-:-4-5-5-)--
-       -a-t-- --c-o-m-.-s-u-n-.-j-a-v-a-f-x-.-a-p-p-l-i-c-at-i-o-n-.-P-l-a-t-f-o-r-m-I-m-p-llma
mbda$runLater$10(PlatformImpl.java:428)
        at java.security.AccessController.doPrivileged(AccessController.java:98)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 3 more
```
although executing it in a console results in a better readable stack trace:
```bash
daniel@ghua-xps15:~/git/other/packagetest/target/client/x86_64-linux$ ./package-test 
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class ch.cnlab.jfx.test.FXApp
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoSuchMethodException: ch.cnlab.jfx.test.FXApp.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getConstructor(DynamicHub.java:2151)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:801)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.security.AccessController.doPrivileged(AccessController.java:98)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 3 more
```
I think, there are issues with the Kotlin code, although I'm not sure, what exactly the problem is.

**Comment by jperedadnr** [comment]
Looks like mvnrepository.com requires some time to be updated, but 13.0.2 is available from Maven Central, and using the maven plugin you should be able to use it.

Glad that you could compile and link (hopefully the message was clear enough to give you a hint on how to solve it).

About runtime failures: you will find some issues that you should be able to solve, usually related to reflection. You need to tell GraalVM which classes/methods/fields are required.

There is a reflection list that you can set in the plugin with class name that require full access. Try:

```
...
<reflectionList>
    <list>ch.cnlab.jfx.test.FXApp</list>
</reflectionList>
...
```
build and run again. If you find more failing classes/methods/fields, you can add those classes to the list.
 
(Also, update JavaFX plugin to 0.0.4 and Client plugin to 0.0.12)

**Comment by bgmf** [comment]
I think you mean Client plugin 0.1.12, right? The same as with 13.0.2 - can't find it, yet. JavaFX plugin 0.0.4 can be found, though.

Thanks for the tip with the `<reflectionList>` entries - I really only had to add this one file! Now it starts in holy `graal` 0.3s (usr time) against 2.1s (usr time) when using a `jpackage`d version of the tool! Nice!

Since the application was purely for "fun", testing the JavaFX-plugin and `jpackage` in conjunction with a simple modularized Kotlin app, there is not much more to expect. But I'm excited to get this far.

Thanks a lot @jperedadnr !

**Comment by jperedadnr** [comment]
Yes, sorry, 0.1.12

I can get 13.0.2 from Maven central with the JavaFX plugins.

Glad that you have solved the issue and works for you.
