### ISSUE TITLE
Fatal error: org.graalvm.compiler.debug.GraalError: LLVM compilation failed for batch 3. Use -H:LLVMBatchesPerThread=-1 to compile each method individually.

### ISSUE THREAD

**Issue by shashaanktulsyan** [gluonhq/client-maven-plugin#129]
As I was not able to get the HelloGluon to build for 
I was trying to build HelloFX sample with android target.
This are my environment variables
```
GRAALVM_HOME=/home/sharabheshwara/Development/graalvm/graalvm-svm-linux-20.0.0-ea+20
JAVA_HOME=/usr/lib/jvm/jdk-13.0.2
ANDROID_SDK=/home/sharabheshwara/Android/Sdk
ANDROID_NDK=/home/sharabheshwara/Android/Sdk/ndk/21.0.6113669
```
I am getting the following error
``Fatal error: org.graalvm.compiler.debug.GraalError: LLVM compilation failed for batch 3 (f21027-f28033). Use -H:LLVMBatchesPerThread=-1 to compile each method individually. (/mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1582353487305/llvm/b3o.bc): 2
``
I guess I have to add this option ``-H:LLVMBatchesPerThread=-1`` somehow and retry. Am I headed in the right direction?

```
user@ubuntu1604wsl:/mnt/f/client-samples-gluon-mvn/Maven/HelloFX$ mvn client:compile
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.14:compile (default-cli) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Nothing to compile - all classes are up to date
We will now compile your code for aarch64-linux-android. This may take some time.
Shutdown Server(pid: 1749, port: 51323)
Build on Server(pid: 2627, port: 51829)*
[hellofx.hellofx:2627]    classlist:  11,102.09 ms,  1.00 GB
[hellofx.hellofx:2627]        (cap):   1,715.32 ms,  1.00 GB
[hellofx.hellofx:2627]        setup:  12,150.04 ms,  1.00 GB
[hellofx.hellofx:2627]   (typeflow):  97,200.04 ms,  2.93 GB
[hellofx.hellofx:2627]    (objects):  61,875.39 ms,  2.93 GB
[hellofx.hellofx:2627]   (features):   7,390.37 ms,  2.93 GB
[hellofx.hellofx:2627]     analysis: 171,747.14 ms,  2.93 GB
[hellofx.hellofx:2627]     (clinit):   3,536.87 ms,  3.01 GB
[hellofx.hellofx:2627]     universe:  13,265.57 ms,  3.01 GB
[hellofx.hellofx:2627]      (parse):  28,480.14 ms,  3.05 GB
[hellofx.hellofx:2627]     (inline):  20,522.06 ms,  3.08 GB
[hellofx.hellofx:2627]    (compile): 161,358.66 ms,  3.09 GB
[hellofx.hellofx:2627]    (bitcode): 295,235.75 ms,  3.09 GB
[hellofx.hellofx:2627]    (prelink): 177,068.92 ms,  3.09 GB
[hellofx.hellofx:2627]       (llvm):  35,356.20 ms,  3.09 GB
[hellofx.hellofx:2627]      compile: 720,206.23 ms,  3.09 GB
Fatal error: org.graalvm.compiler.debug.GraalError: LLVM compilation failed for batch 3 (f21027-f28033). Use -H:LLVMBatchesPerThread=-1 to compile each method individually. (/mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1582353487305/llvm/b3o.bc): 2
        at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.llvmCompile(LLVMNativeImageCodeCache.java:525)
        at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.lambda$compileBitcodeBatches$9(LLVMNativeImageCodeCache.java:447)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
Compilation failed with result = 1
Compilation failed. See error printed above.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:02 min
[INFO] Finished at: 2020-02-22T12:23:28+05:30
[INFO] Final Memory: 14M/57M
[INFO] ------------------------------------------------------------------------
```

Before that I got this error. 
So I added llvm bin folder to the PATH with the hope that it will fix the problem. 
```
LLVM_FOR_GRAAL="$HOME/Development/graalvm/graalvm-svm-linux-20.0.0-ea+20/lib/llvm/bin"
PATH="$HOME/bin:$HOME/.local/bin:$JAVA_HOME/bin:$PATH:$LLVM_FOR_GRAAL"
```

```
user@ubuntu1604wsl:/mnt/c/Users/user$ cd /mnt/f/client-samples-gluon-mvn/Maven/HelloFX
user@ubuntu1604wsl:/mnt/f/client-samples-gluon-mvn/Maven/HelloFX$ mvn client:compile
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.14:compile (default-cli) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/classes
We will now compile your code for aarch64-linux-android. This may take some time.
Shutdown Server(pid: 1195, port: 50618)
Build on Server(pid: 2303, port: 51709)*
[hellofx.hellofx:2303]    classlist:  18,161.98 ms,  1.00 GB
[hellofx.hellofx:2303]        (cap):   1,115.36 ms,  1.00 GB
[hellofx.hellofx:2303]        setup:  10,807.94 ms,  1.00 GB
[hellofx.hellofx:2303]   (typeflow): 112,274.46 ms,  2.95 GB
[hellofx.hellofx:2303]    (objects):  86,600.64 ms,  2.95 GB
[hellofx.hellofx:2303]   (features):  15,913.33 ms,  2.95 GB
[hellofx.hellofx:2303]     analysis: 222,872.44 ms,  2.95 GB
[hellofx.hellofx:2303]     (clinit):   3,013.58 ms,  3.02 GB
[hellofx.hellofx:2303]     universe:   9,953.95 ms,  3.02 GB
[hellofx.hellofx:2303]      (parse):  20,345.44 ms,  3.03 GB
[hellofx.hellofx:2303]     (inline):  17,578.97 ms,  3.05 GB
[hellofx.hellofx:2303]    (compile): 129,371.75 ms,  3.07 GB
[hellofx.hellofx:2303]    (bitcode): 258,460.41 ms,  3.07 GB
[hellofx.hellofx:2303]    (prelink):      53.66 ms,  3.07 GB
[hellofx.hellofx:2303]      compile: 426,940.92 ms,  3.07 GB
Fatal error: org.graalvm.compiler.debug.GraalError: java.io.IOException: Cannot run program "llvm-link" (in directory "/mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1582351805110/llvm"): error=2, No such file or directory
        at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.llvmLink(LLVMNativeImageCodeCache.java:555)
        at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.lambda$createBitcodeBatches$8(LLVMNativeImageCodeCache.java:433)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.io.IOException: Cannot run program "llvm-link" (in directory "/mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1582351805110/llvm"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.llvmLink(LLVMNativeImageCodeCache.java:544)
        ... 12 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 14 more
Error: Image build request failed with exit status 1
Compilation failed with result = 1
Compilation failed. See error printed above.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:04 min
[INFO] Finished at: 2020-02-22T11:51:18+05:30
[INFO] Final Memory: 21M/77M
[INFO] ------------------------------------------------------------------------
user@ubuntu1604wsl:/mnt/f/client-samples-gluon-mvn/Maven/HelloFX$ ls /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1582351805110/llvm
f0.bc      f12234.bc  f14469.bc  f16702.bc  f18937.bc  f2116.bc   f23403.bc  f25638.bc  f3300.bc  f5535.bc  f776.bc
f10000.bc  f12235.bc  f1446.bc   f16703.bc  f18938.bc  f21170.bc  f23404.bc  f25639.bc  f3301.bc  f5536.bc  f7770.bc
.........
f12233.bc  f14468.bc  f16701.bc  f18936.bc  f21169.bc  f23402.bc  f25637.bc  f32.bc     f5534.bc  f7769.bc
```

**Comment by shashaanktulsyan** [comment]
I read in Gerrit Grunwald's website that he used Ubuntu 18.04 while compiling spacex, so I thought of trying Ubuntu 18.04 WSL. Another slightly different thing I did from the past was, I installed ndk-bundle instead of side-by-side (the version is the same though, version 21.0.6113669 ). 
Was able to compile and link. 
This is the closest I was able to get so far from running javafx on android. 
I was compiling the HelloFX example. 
However on running, it is saying ``segmentation fault 139``

```shell
cd client-samples-gluon-mvn\Maven\HelloFX\target\client\aarch64-android 
adb push hellofx /data/local/tmp
adb shell
______:/ $ cd data/local/tmp
cd data/local/tmp
______:/data/local/tmp $ chmod 500 hellofx
chmod 500 hellofx
______:/data/local/tmp $ ./hellofx
./hellofx
Segmentation fault
139|______:/data/local/tmp $ chmod +x hellofx
chmod +x hellofx
______:/data/local/tmp $ ./hellofx
./hellofx
Segmentation fault
139|______:/data/local/tmp $

```

Any tip, suggestion would be highly appreciated.
