### ISSUE TITLE
Compile failed on windows: Missing reflectionconfig-javafx-x86_64-windows.json

### ISSUE THREAD

**Issue by Glavo** [gluonhq/client-maven-plugin#131]
GraalVM 20.0.0 improves native-image support on Windows and provides pre-built packages for native-image components on Windows. However, an error occurred when I tried to compile with this plugin:
```
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.glavo:ClassViewer >------------------------
[INFO] Building ClassViewer 3.9
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.15:compile (default-cli) @ ClassViewer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 48 resources
[INFO] Copying 5 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 127 source files to C:\Users\Glavo\Projects\ClassViewer\ClassViewer-v3\target\classes
We will now compile your code for x86_64-microsoft-windows. This may take some time.
java.io.IOException: Missing a reflection configuration file named reflectionconfig-javafx-x86_64-windows.json
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.createReflectionConfig(AbstractTargetConfiguration.java:488)
[INFO] BUILD FAILURE
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:143)
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:196)
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:69)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[INFO] Total time:  5.468 s
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[INFO] Finished at: 2020-02-25T00:54:24+08:00
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.15:compile (default-cli) on project ClassViewer: Error: Missing a reflection configuration file named reflectionconfig-javafx-x86_64-windows.json -> [Help 1]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] For more information about the errors and possible solutions, please read the following articles:
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:23 min
[INFO] Finished at: 2020-02-25T00:54:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.15:build (default-cli) on project ClassViewer: Error, client:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tiainen** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/581
