### ISSUE TITLE
Build for older android phones 

### ISSUE THREAD

**Issue by shashaanktulsyan** [gluonhq/client-maven-plugin#148]
The documentation here says https://docs.gluonhq.com/client/ to use android 27 for building the apps. Thanks to the gluon team, was able to successfully compile and run an app on recent mobile phones. But practically I need on a bit older phones. With what we already have in gluon-client plugin, is it possible to target older android phones ? Particularly at-least APL LEVEL 21 ? Or right now android api 27 is the lower limit ?

**Comment by jperedadnr** [comment]
You can still set the `android:targetSdkVersion` to 21 in the AndroidManifest.xml file of your project. Note: That won't allow you to publish the app into the Play Store (they require 28).

**Comment by shashaanktulsyan** [comment]
The HelloFX app didn't run on a Lenovo mobile running Android Nougat so I presumed that this might be the reason. But looking at the autogenerated AndroidManifest.xml ``client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/dalvik/AndroidManifest.xml`` it seems it is already set to 21. 
```
<?xml version='1.0'?>
<manifest xmlns:a='http://schemas.android.com/apk/res/android' package='hello.hellofx' a:versionCode='1' a:versionName='1.0'>
    <supports-screens a:xlargeScreens="true"/>
    <uses-sdk a:minSdkVersion="21" a:targetSdkVersion="21"/>
    <application a:label='hellofx'>
        <activity a:name='com.gluonhq.helloandroid.MainActivity' a:configChanges="orientation|keyboardHidden">
             <intent-filter>
                <category a:name='android.intent.category.LAUNCHER'/>
                <action a:name='android.intent.action.MAIN'/>
             </intent-filter>
        </activity>
    </application>
</manifest>
```
Am I missing something?
Is there some other place where we need to set this to 21 ? In the main ``pom.xml`` ? 
Or it is just that there is some specific issue with that particular phone. 
It did run well on two other phones that I tested with.

**Comment by jperedadnr** [comment]
Make sure you have the latest version of the plugin (0.1.17 now), it uses android target 28.
This is the default manifest: https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/AndroidManifest.xml

You will have to run mvn client:build to generate it in target/client/aarch64-android/gvm/gensrc/android

Then copy that android folder to src/android, and then you can modify that manifest and the icons.

**Comment by shashaanktulsyan** [comment]
Thank you I am trying it out now. But I am wondering, I was using version 0.1.14 and there it was already set to 21 by default, which means the apk produced already had this setting, so then I am wondering if there are any better chance for this to work on this older phone by migrating to 0.1.17 and then changing the android sdk version. 
Anyhow it is good to get to know all these new small small things.

**Comment by shashaanktulsyan** [comment]
Failed saying cannot find llc. 
``` Caused by: java.io.IOException: Cannot run program "llc" (in directory "/mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/tmp/SVM-1584445735797/llvm"): error=2, No such file or directory```

There is no binary with that name in 
``\home\user\Development\graalvm\graalvm-svm-linux-20.0.0-ea+20\lib\llvm\bin``
I see ``lld`` and ``lli``there. 

Do I need to download an updated graalvm ?

**Comment by tiainen** [comment]
Yes, you should download https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1-latest.zip. That one bundles llc, so we no longer need to download it separately.

**Comment by shashaanktulsyan** [comment]
Having issues with this newer version :| 
And the build with 0.1.14 is not running no quiet a few devices which I am finding practically around.

```
:/mnt/f/client-samples-gluon-mvn/Maven/HelloFX$ mvn clean client:build
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellofx ---
[INFO] Deleting /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.17:build (default-cli) @ hellofx ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> client-maven-plugin:0.1.17:compile (default-cli) > process-classes @ hellofx >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofx ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/classes
[INFO]
[INFO] <<< client-maven-plugin:0.1.17:compile (default-cli) < process-classes @ hellofx <<<
[INFO]
[INFO]
[INFO] --- client-maven-plugin:0.1.17:compile (default-cli) @ hellofx ---
We will now compile your code for aarch64-linux-android. This may take some time.
[Tue Mar 17 19:29:13 IST 2020][INFO] [SUB] [hellofx.hellofx:1318]    classlist:  12,309.32 ms,  0.96 GB
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB] [hellofx.hellofx:1318]        (cap):     715.72 ms,  0.96 GB
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB] [hellofx.hellofx:1318]        setup:   2,741.61 ms,  0.96 GB
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB] Fatal error:java.lang.NumberFormatException
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:358)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:517)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:116)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:544)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB] Caused by: java.lang.NumberFormatException: null
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.lang.Integer.parseInt(Integer.java:614)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.lang.Integer.parseInt(Integer.java:770)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:82)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:389)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1537)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1033)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:535)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:450)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.075 s
[INFO] Finished at: 2020-03-17T19:29:16+05:30
[INFO] ------------------------------------------------------------------------
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Tue Mar 17 19:29:16 IST 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Tue Mar 17 19:29:16 IST 2020][SEVERE] Process compile failed with result: 1
Check the log files under /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Tue Mar 17 19:29:16 IST 2020][INFO] Logging process [compile] to file: /mnt/f/client-samples-gluon-mvn/Maven/HelloFX/target/client/log/process-compile-1584453556726.log
Compilation failed. See error printed above.
org.apache.maven.plugin.MojoExecutionException: Compilation failed
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:70)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.17:compile (default-cli) on project hellofx: Error: Compilation failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2020-03-17T19:29:16+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.17:build (default-cli) on project hellofx: Error, client:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tiainen** [comment]
That was a [known issue](https://github.com/gluonhq/substrate/issues/443) and has already been fixed. You can either try the snapshot version of this plugin (0.0.18-SNAPSHOT) from the following maven repository: https://nexus.gluonhq.com/nexus/content/repositories/public-snapshots/. Or you wait until we publish a new release (which should be available somewhere later today or tomorrow).

**Comment by shashaanktulsyan** [comment]
@jperedadnr thanks for the tip related editing the android manifest.
I tried all permutations and combinations I could think of, and it is not running on quiet a few phones. I suspect it might to be do with the customization some vendors so. One of the things I tried to run this on is a Samsung Galazy Tab A (2017), Android 8.0 Know API Level 28. It is only saying install failed. I disabled protection from playstore, allowed untrusted code etc. It is installing, and at the end it is just failin and exiting.
It is good to see it run on a few more recent mobile yes.

**Comment by shashaanktulsyan** [comment]
Update 3 : I figured out that, Samsung Galaxy Tab A (2017) has a Qualcomm processor supporting only - armeabi-v7a, armeabi. 

![image](https://user-images.githubusercontent.com/6197269/76957706-4da78580-693c-11ea-8764-360f46642e70.png)

Since we know, that starting August 1, 2019, apps published on Google Play are required to support 64-bit architectures. I thought it was a conservative target to support only armv64-v8a devices. 

However, it seems a lot of vendors are still using 32-bit processors. It feel it would be better to support armeabi-v7a also. Doing a bit of research on this : 
From Google Play Console (supporting a minimum of Android 4.1 and landscape screen):
* x86: 287 devices
* arm64-v8a: 3136 devices
* armeabi-v7a: 11716 devices
Source : https://android.stackexchange.com/a/213663 

Sounds like significant amount of work, and I feel it would be too demanding to ask this to the team already doing so much good work and keeping it all free and open source, but as things are right now to support a large set of target devices for android and to remain compatible with requirements of Google Play both 32-bit and 64-bit binaries have to be bundled together in the APK.
