### ISSUE TITLE
GraalError during compilation in HelloFXML

### ISSUE THREAD

**Issue by tunguski** [gluonhq/client-maven-plugin#153]
I've tried to play a bit with gluon's client-maven-plugin examples - I've got through native compilation on Ubuntu 19.10 for all samples. Yet I wasn't able to perform android native build successfully.

I guess this is only because of my incorrectly setup environment, but I'm unable to spot the issue.

Environment:

```
$ /home/marek/opt/graalvm/bin/java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing)

$ export | grep -Pi "java_home|graalvm_home"
declare -x GRAALVM_HOME="/home/marek/opt/graalvm"
declare -x JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"

# android studio with android platform 10.0 (Q), platform-tools 29.0.6, ndk and android sdk tools 26.1.1
$ export | grep -i android
declare -x ANDROID_SDK="/home/marek/Android/Sdk"
```

For every build, log is very similar - only the class reported in

> Fatal error: org.graalvm.compiler.debug.GraalError: LLVM compilation failed for [...]

changes for every invocation:

```
marek@marek-XPS:~/w/java/client-samples/Maven/HelloFXML$ mvn clean client:build
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellofxml ---
[INFO] Deleting /home/marek/w/java/client-samples/Maven/HelloFXML/target
[INFO] 
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.18:build (default-cli) @ hellofxml ---
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> client-maven-plugin:0.1.18:compile (default-cli) > process-classes @ hellofxml >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofxml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofxml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/marek/w/java/client-samples/Maven/HelloFXML/target/classes
[INFO] 
[INFO] <<< client-maven-plugin:0.1.18:compile (default-cli) < process-classes @ hellofxml <<<
[INFO] 
[INFO] 
[INFO] --- client-maven-plugin:0.1.18:compile (default-cli) @ hellofxml ---
Configuration: ProjectConfiguration{graalPath='/home/marek/opt/graalvm', javaStaticSdkVersion='14-ea+8', javafxStaticSdkVersion='15-ea+gvm16', useJNI=true, useJavaFX=true, usePrismSW=false, enableCheckHash=true, targetTriplet=aarch64-linux-android, hostTriplet=x86_64-linux-linux, backend='null', bundlesList=[], resourcesList=[], reflectionList=[], jniList=[], initBuildTimeList=[], runtimeArgsList=null, releaseSymbolsList=null, appName='hellofxml', iosConfiguration='IosConfiguration{skipSigning=false, providedSigningIdentity='null', providedProvisioningProfile='null', simulatorDevice='null'}', mainClassName='hellofx.HelloFXML', classpath='/home/marek/w/java/client-samples/Maven/HelloFXML/target/classes:/home/marek/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1-linux.jar:/home/marek/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1.jar:/home/marek/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1-linux.jar:/home/marek/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1.jar:/home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-linux.jar:/home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar:/home/marek/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1-linux.jar:/home/marek/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1.jar'}
[Mon Mar 23 00:08:04 CET 2020][INFO] ==================== COMPILE TASK ====================
[Mon Mar 23 00:08:04 CET 2020][FINE] PB Command for check version: /home/marek/opt/graalvm/bin/java -version
[Mon Mar 23 00:08:04 CET 2020][FINE] Start process check version...
[Mon Mar 23 00:08:04 CET 2020][FINE] [SUB] openjdk version "11.0.6" 2020-01-14
[Mon Mar 23 00:08:04 CET 2020][FINE] [SUB] OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
[Mon Mar 23 00:08:04 CET 2020][FINE] [SUB] OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
[Mon Mar 23 00:08:04 CET 2020][FINE] Result for check version: 0
[Mon Mar 23 00:08:04 CET 2020][INFO] We will now compile your code for aarch64-linux-android. This may take some time.
[Mon Mar 23 00:08:04 CET 2020][FINE] Extracting native libs to: /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/lib
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/launcher.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/javafx_adapter.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/touch_events.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/glibc_shim.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/attach_adapter.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Looking for resource: /native/android/c/grandroid.h
[Mon Mar 23 00:08:04 CET 2020][FINE] PB Command for compile-additional-sources: /home/marek/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -c -DGVM_VERBOSE -target aarch64-linux-android -I. -I/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/hellofxml launcher.c javafx_adapter.c touch_events.c glibc_shim.c attach_adapter.c
[Mon Mar 23 00:08:04 CET 2020][FINE] Start process compile-additional-sources...
[Mon Mar 23 00:08:05 CET 2020][FINE] Result for compile-additional-sources: 0
[Mon Mar 23 00:08:05 CET 2020][FINE] PB Command for jar: jar cf /tmp/classes16326234330175993543/classes.jar -C /home/marek/w/java/client-samples/Maven/HelloFXML/target/classes .
[Mon Mar 23 00:08:05 CET 2020][FINE] Start process jar...
[Mon Mar 23 00:08:05 CET 2020][FINE] Result for jar: 0
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning for init build time files
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-linux.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /tmp/classes16326234330175993543/classes.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning for reflection files
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar::META-INF/substrate/config/reflectionconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar::META-INF/substrate/config/reflectionconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-linux.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/reflectionconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/reflectionconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/reflectionconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /tmp/classes16326234330175993543/classes.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning for JNI files
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-linux.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/jniconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/jniconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/jniconfig.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Adding classes from /home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar::META-INF/substrate/config/jniconfig-aarch64-android.json
[Mon Mar 23 00:08:05 CET 2020][FINE] Scanning /tmp/classes16326234330175993543/classes.jar
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/AArch64LibCHelperDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/AMD64LibCHelperDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/BuiltinDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/JNIHeaderDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/LibFFIHeaderDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/LLVMDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] Looking for resource: /native/android/cap/PosixDirectives.cap
[Mon Mar 23 00:08:05 CET 2020][FINE] PB Command for compile: /home/marek/opt/graalvm/bin/native-image --report-unsupported-elements-at-runtime -Djdk.internal.lambda.eagerlyInitialize=false --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets --features=org.graalvm.home.HomeFinderFeature -H:TempDirectory=/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/tmp -H:+PrintAnalysisCallTree -H:Log=registerResource: -H:ReflectionConfigurationFiles=/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/reflectionconfig-aarch64-android.json -H:JNIConfigurationFiles=/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/jniconfig-aarch64-android.json -H:ResourceConfigurationFiles=/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/resourceconfig-aarch64-android.json -H:CompilerBackend=llvm -H:-SpawnIsolates -Dsvm.targetArch=aarch64 -H:+UseOnlyWritableBootImageHeap -H:+UseCAPCache -H:CAPCacheDir=/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/capcache -H:CustomLD=/home/marek/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld -H:IncludeResourceBundles=hellofx.hello,com/sun/javafx/scene/control/skin/resources/controls,com.sun.javafx.tk.quantum.QuantumMessagesBundle -Dsvm.platform=org.graalvm.nativeimage.Platform$LINUX_AARCH64 -cp /home/marek/w/java/client-samples/Maven/HelloFXML/target/classes:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-base.jar:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-controls.jar:/home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-linux.jar:/home/marek/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar:/home/marek/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/android-aarch64/sdk/lib/javafx-graphics.jar -H:LLVMBatchesPerThread=-1 hellofx.HelloFXML
[Mon Mar 23 00:08:05 CET 2020][FINE] Start process compile...
[Mon Mar 23 00:08:08 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]    classlist:   2,812.20 ms,  1.23 GB
[Mon Mar 23 00:08:09 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]        (cap):     291.31 ms,  1.23 GB
[Mon Mar 23 00:08:10 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]        setup:   1,891.77 ms,  1.23 GB
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB] [Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB] [thread:28] scope: ForkJoinPool-4-worker-3
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB]   [thread:28] scope: ForkJoinPool-4-worker-3.registerResource
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB]   ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB]   [thread:28] scope: ForkJoinPool-4-worker-3.registerResource
[Mon Mar 23 00:08:23 CET 2020][INFO] [SUB]   Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
[Mon Mar 23 00:09:24 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]   (typeflow):  25,289.36 ms,  9.25 GB
[Mon Mar 23 00:09:24 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]    (objects):  44,070.56 ms,  9.25 GB
[Mon Mar 23 00:09:24 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]   (features):   2,385.57 ms,  9.25 GB
[Mon Mar 23 00:09:24 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]     analysis:  73,791.30 ms,  9.25 GB
[Mon Mar 23 00:09:37 CET 2020][INFO] [SUB] Printing call tree to /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/hellofxml/reports/call_tree_hellofx.hellofxml_20200323_000937.txt
[Mon Mar 23 00:09:40 CET 2020][INFO] [SUB] Printing list of used methods to /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/hellofxml/reports/used_methods_hellofx.hellofxml_20200323_000940.txt
[Mon Mar 23 00:09:40 CET 2020][INFO] [SUB] Printing list of used classes to /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/hellofxml/reports/used_classes_hellofx.hellofxml_20200323_000940.txt
[Mon Mar 23 00:09:40 CET 2020][INFO] [SUB] Printing list of used packages to /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/hellofxml/reports/used_packages_hellofx.hellofxml_20200323_000940.txt
[Mon Mar 23 00:09:43 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]     (clinit):   1,037.91 ms,  9.84 GB
[Mon Mar 23 00:09:43 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]     universe:   2,441.33 ms,  9.84 GB
[Mon Mar 23 00:09:49 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]      (parse):   5,738.30 ms,  9.84 GB
[Mon Mar 23 00:09:53 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]     (inline):   3,777.69 ms,  9.84 GB
[Mon Mar 23 00:10:31 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]    (compile):  38,308.60 ms, 10.03 GB
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]    (bitcode):     527.06 ms, 10.03 GB
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]    (prelink):       0.03 ms, 10.03 GB
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]       (llvm):     269.07 ms, 10.03 GB
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] [hellofx.hellofxml:7068]      compile:  49,336.41 ms, 10.03 GB
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] Fatal error: org.graalvm.compiler.debug.GraalError: LLVM compilation failed for javafx.fxml.FXMLLoader.loadType(java.lang.String, boolean) (/home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/tmp/SVM-1584918489421/llvm/f10606o.bc): 1
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.llvmCompile(LLVMNativeImageCodeCache.java:524)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.lambda$compileBitcodeBatches$8(LLVMNativeImageCodeCache.java:446)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Mon Mar 23 00:10:32 CET 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Mon Mar 23 00:10:33 CET 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Mon Mar 23 00:10:33 CET 2020][FINE] Result for compile: 1
[Mon Mar 23 00:10:33 CET 2020][SEVERE] Process compile failed with result: 1
Check the log files under /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Mon Mar 23 00:10:33 CET 2020][INFO] Logging process [compile] to file: /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/log/process-compile-1584918633438.log
[Mon Mar 23 00:10:33 CET 2020][SEVERE] Compiling failed.
Check the log files under /home/marek/w/java/client-samples/Maven/HelloFXML/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:30 min
[INFO] Finished at: 2020-03-23T00:10:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.18:compile (default-cli) on project hellofxml: Compiling failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:33 min
[INFO] Finished at: 2020-03-23T00:10:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.18:build (default-cli) on project hellofxml: Error, client:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
marek@marek-XPS:~/w/java/client-samples/Maven/HelloFXML$
```

I'll appreciate any suggestion what I may be missing here.

Thanks!

**Comment by tunguski** [comment]
Ok, I've got through it when replaced graalvm with gluon version `graalvm-svm-linux-20.1.0-ea+26.zip`
