### ISSUE TITLE
Cant get SQLite to work

### ISSUE THREAD

**Issue by NO-ob** [gluonhq/client-maven-plugin#178]
I'm trying to get SQLite to work but it doesn't. I have added 
<list>java.sql.Connection</list>
<list>java.sql.DriverManager</list>
<list>java.sql.Statement</list>
<list>java.sql.SQLException</list>
<list>java.sql.ResultSet</list>

But when the program tries to connect to the database I get an SQLException which says "Error Opening Connection". It works when running as JavaFx so i'm not sure what the issue is. 

I am using the sqlite-jdbc maven plugin

**Comment by mipastgt** [comment]
In order to get that working I head to add

                    <jniList>
                        <list>org.sqlite.core.DB</list>
                        <list>org.sqlite.core.NativeDB</list>
                        <list>org.sqlite.BusyHandler</list>
                        <list>org.sqlite.Function</list>
                        <list>org.sqlite.ProgressHandler</list>
                        <list>org.sqlite.Function$Aggregate</list>
                        <list>org.sqlite.Function$Window</list>
                        <list>org.sqlite.core.DB$ProgressObserver</list>
                    </jniList>

                    <resourcesList>
                        <list>org/sqlite/native/${sqlite.platform}/${os.arch}/.*</list>
                    </resourcesList>

and I did not use any SQLite plugin because I don't know what the interaction with the client-maven-plugin would be. ${sqlite.platform} must be set correctly for your platform. (FreeBSD, Linux, Mac, Windows)

**Comment by cbm64chris** [comment]
I am looking at a similar problem. I am trying to access a SQLite DB on IOS that I create inside private storage at runtime. Works fine for desktop but I am getting;

```
Caused by: java.lang.Exception: No native library is found for os.name=iOS and os.arch=arm. path=/org/sqlite/native/iOS/arm
[Sat Jun 20 17:40:43 BST 2020][INFO] [SUB] 	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:335)
[Sat Jun 20 17:40:43 BST 2020][INFO] [SUB] 	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
[Sat Jun 20 17:40:43 BST 2020][INFO] [SUB] 	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
[Sat Jun 20 17:40:43 BST 2020][INFO] [SUB] 	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
```

I am pulling in 3.31.1 of SQLite in maven, looking at the packages there is no iOS native jni. Is this currently possible?

**Comment by cbm64chris** [comment]
Wanted to circle back around here  - I choose to implement a native java implementation of the SQLite driver (SQLJet), it works just fine on [iOS](https://github.com/cbm64chris/weight-converter/blob/storage/src/main/java/com/fluffy/luffs/weight/converter/storage/Database.java).

**Comment by mipastgt** [comment]
But SQLJet is not a real database engine.

_SQLJet does not support SQL queries; there is an API to work with the database on a lower level._

But for some use-cases this may be ok.

**Comment by cbm64chris** [comment]
Agreed, but for basic creation, selection, and deletion without the native JNI it does the job fine.

**Comment by mipastgt** [comment]
Except the license which excludes any commercial use.

**Comment by kojojo1** [comment]
I'm struggling with the same issue. @mipastgt Could you provide the complete example pom.xml file for one platform (Mac for example) . It would be awesome.

**Comment by mipastgt** [comment]
Sorry, but I cannot provide you with more than I have posted already.
