### ISSUE TITLE
NumberFormatException in native-image

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#208]
Since I upgraded to the latest version of all tooling (client-maven-plugin, graalvm) I cannot build my app for Android anymore. I can still build all my code for the Linux host target but as soon as I switch the target from host to android I get a NumberFormatException during the build.
```
...
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]    classlist:   3,969.71 ms,  0.94 GB
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]        (cap):     190.07 ms,  0.93 GB
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]        setup:     704.47 ms,  0.93 GB
Fatal error:java.lang.NumberFormatException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:478)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
	at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
	at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
	at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
	at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
	at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
	at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:83)
	at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:520)
	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1536)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1034)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:867)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:551)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:466)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
```
The bad thing is that the error message is not providing any context. No filename, no linenumber, no String. So it is impossible for me track this down.

I remember that I had a similar issue several months ago and there it was caused by an unexpected version number of some Android tool or library which did not consist of pure integers but I have no idea whether this is related to this issue or not.

**Comment by mipastgt** [comment]
I raised an issue for this in GraalVM native-image too: https://github.com/oracle/graal/issues/2677

**Comment by lazar-mitrovic** [comment]
https://github.com/gluonhq/substrate/pull/697 closes this issue

**Comment by mipastgt** [comment]
Great, thank you.

**Comment by mipastgt** [comment]
I just wanted to confirm that this works now with the latest snapshots but now there are other issues.

**Comment by jperedadnr** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/697
