### ISSUE TITLE
Could not find option 'UseBionicC'

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#211]
After https://github.com/gluonhq/client-maven-plugin/issues/208 was fixed in the latest snapshots I tried to build my app again but immediately stumbled over https://github.com/gluonhq/substrate/issues/688 . In order to get the fix for that I installed the latest GraalVM snapshot form 20200718. But now the build fails with Could not find option 'UseBionicC'.

Here is the full context.
```
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] Error: Could not find option 'UseBionicC'. Use -H:PrintFlags= to list all available options.
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
[Mon Jul 20 12:28:55 CEST 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
[Mon Jul 20 12:28:55 CEST 2020][FINE] Result for compile: 1
[Mon Jul 20 12:28:55 CEST 2020][SEVERE] Process compile failed with result: 1
```
This option is added by the plugin.

**Comment by jperedadnr** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/701
