### ISSUE TITLE
Homebrew not found

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/client-maven-plugin#225]
I encounter weird issue here while I run `mvn client:run` on the plugin:

```
[Thu Aug 13 12:02:21 SGT 2020][INFO] ==================== RUN TASK ====================
[Thu Aug 13 12:02:21 SGT 2020][FINE] PB Command for check brew: which brew
[Thu Aug 13 12:02:21 SGT 2020][FINE] Start process check brew...
[Thu Aug 13 12:02:21 SGT 2020][FINE] Result for check brew: 1
[Thu Aug 13 12:02:21 SGT 2020][SEVERE] Process check brew failed with result: 1
Check the log files under /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Thu Aug 13 12:02:21 SGT 2020][INFO] Logging process [check brew] to file: /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/log/process-check brew-1597291341729.log
[Thu Aug 13 12:02:21 SGT 2020][SEVERE] Homebrew not found
Check the log files under /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
java.lang.RuntimeException: Open a terminal and run the following command to install Homebrew: 

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	at com.gluonhq.substrate.util.ios.Deploy.checkPrerequisites(Deploy.java:73)
	at com.gluonhq.substrate.util.ios.Deploy.<init>(Deploy.java:59)
	at com.gluonhq.substrate.target.IosTargetConfiguration.runUntilEnd(IosTargetConfiguration.java:199)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeRun(SubstrateDispatcher.java:486)
	at com.gluonhq.NativeRunMojo.execute(NativeRunMojo.java:45)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I check the log file:

```
Process
=======
check brew

Command Line
============
which brew

Output
======


Result
======
result: 1
```

I run `which brew` in terminal:

```
$ which brew
/usr/local/bin/brew
```

Pretty sure I have Homebrew in my Mac machine, I even already installed `libusbmuxd` and `libimobiledevice` successfully. But not sure why maven plugin keep cannot find it.

**Comment by jperedadnr** [comment]
That is definitely weird. The internal process that runs `which brew` should return the same as when you run it from a terminal. 
Checking this [post](https://discourse.brew.sh/t/which-brew-doesnot-return-anything/4375/2), there could be a possible issue  with your `$PATH` environment variable. Can you check it out?

**Comment by samyc1201** [comment]
@jperedadnr 

Previously I build via Eclipse Maven plugin, thought it will read the default ".bash_profile" configuration but it is not... 

I do maven build via terminal, it is working fine... thanks.
