### ISSUE TITLE
org.dom4j.DocumentException

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/client-maven-plugin#243]
In pom.xml:
`<dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.3</version>
        </dependency>`

code :
`SAXReader reader = SAXReader.createDefault();
Document document = reader.read(new File("d:\\a.xml););
System.out.println(document );`
in idea, 
`org.dom4j.tree.DefaultElement@6a4da98c [Element: <Services attributes: []/>]`

run : `mvn clean client:build client:run`
the client-debug0.log shows: 
`org.dom4j.DocumentException
	at org.dom4j.io.SAXReader.read(SAXReader.java:464)
 	at org.dom4j.io.SAXReader.read(SAXReader.java:246)`

so the dom4j can't read local file ?

**Comment by EvokeAngle** [comment]
org.dom4j.DocumentException
 	at org.dom4j.io.SAXReader.read(SAXReader.java:464)
 	at org.dom4j.io.SAXReader.read(SAXReader.java:246)
 	at com.kedong.hmi.platform.serviceinterface.context.utils.KeyIDModelConfig.initKeyIDModelConfig(KeyIDModelConfig.java:36)
 	at com.kedong.hmi.platform.serviceinterface.context.utils.KeyIDModelConfig.getInstance(KeyIDModelConfig.java:23)
 	at com.kedong.hmi.platform.serviceinterface.context.ContextFactory.<clinit>(ContextFactory.java:31)
 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
 	at com.kedong.hmi.platform.serviceinterface.doublelongmiddata.utils.MiddataTool.getContextID(MiddataTool.java:52)
 	at com.kedong.hmi.platform.serviceinterface.doublelongmiddata.transitory.MiddataMetaDataService.readSystemInfoForMetaData(MiddataMetaDataService.java:381)
 	at com.kedong.hmi.platform.serviceinterface.middatainterface.IMiddataMetaDataService.readSystemInfoForMetaData(IMiddataMetaDataService.java:165)
 	at com.kedong.hmi.platform.rtdb.controller.SecondToolbarController.initComboBoxData(SecondToolbarController.java:90)
 	at com.kedong.hmi.platform.rtdb.view.SecondToolBarView.init(SecondToolBarView.java:76)
 	at com.kedong.hmi.platform.rtdb.view.SecondToolBarView.<init>(SecondToolBarView.java:39)
 	at com.kedong.hmi.platform.rtdb.view.MainView.init(MainView.java:62)
 	at com.kedong.hmi.platform.rtdb.view.MainView.<init>(MainView.java:48)
 	at com.kedong.hmi.platform.rtdb.Main.start(Main.java:31)
 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
 	at java.security.AccessController.doPrivileged(AccessController.java:101)
 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
 	at java.lang.Thread.run(Thread.java:834)
 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
 	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
 Caused by: java.lang.NullPointerException
 	at org.dom4j.tree.NamespaceStack.createNamespace(NamespaceStack.java:407)
 	at org.dom4j.tree.NamespaceStack.getQName(NamespaceStack.java:211)
 	at org.dom4j.io.SAXContentHandler.startElement(SAXContentHandler.java:226)
 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
 	at org.dom4j.io.SAXReader.read(SAXReader.java:445)
 	... 27 more
 That's all  .

**Comment by EvokeAngle** [comment]
`<?xml version="1.0"?>
<note>
<from>Jani</from>
<to>Tove</to>
<message>Norwegian: æøå. French: êèé</message>
</note>`

**Comment by EvokeAngle** [comment]
`                   <nativeImageArgs>                 
                        <nativeImageArg>--initialize-at-build-time=org.dom4j.Namespace</nativeImageArg>
                        <nativeImageArg>--initialize-at-build-time=org.dom4j.QName</nativeImageArg>
                    </nativeImageArgs>`
I solved this problem by adding this  Thank you  .
