### ISSUE TITLE
com.oracle.svm.core.util.UserError$UserException: Error parsing resource configuration in resourceconfig-arm64-ios.json

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/client-maven-plugin#247]
I follow this doc: https://docs.gluonhq.com/client/#_resources

I run tracing agent to collect the resources being used in HotSpot, after that I copy the file from `resource-config.json` to `src/main/resources/META-INF/substrate/config/resourceconfig.json`

The content is as below:

```
{
  "resources":[
    {"pattern":"\\QProcessorMetadata.txt\\E"}, 
    {"pattern":"\\Qres/pdf/rs/[AAA] BBB CCC DDD (EEE) V1.4 2019 09 05.pdf\\E"}
  ],
  "bundles":[
    {"name":"com.sun.javafx.tk.quantum.QuantumMessagesBundle"}, 
    {"name":"errors/errors"}
  ]
}

```

When I compile, I got error as below:

```
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] Error: Error parsing resource configuration in /Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/resourceconfig-arm64-ios.json:
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] line 20 column 47 Trailing comma is not allowed in JSON
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationFiles.
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing resource configuration in /Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/resourceconfig-arm64-ios.json:
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] line 20 column 47 Trailing comma is not allowed in JSON
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationFiles.
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Fri Aug 28 16:07:16 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:138)

```

I checked the content of this file `HelloFX webview/target/client/arm64-ios/gvm/resourceconfig-arm64-ios.json`

```
{
  "resources": [
    {"pattern": ".*\\.png$"},
    {"pattern": ".*\\.jpg$"},
    {"pattern": ".*\\.jpeg$"},
    {"pattern": ".*\\.gif$"},
    {"pattern": ".*\\.bmp$"},
    {"pattern": ".*\\.ttf$"},
    {"pattern": ".*\\.raw$"},
    {"pattern": ".*\\.xml$"},
    {"pattern": ".*\\.fxml$"},
    {"pattern": ".*\\.css$"},
    {"pattern": ".*\\.gls$"},
    {"pattern": ".*\\.json$"},
    {"pattern": ".*\\.dat$"},
    {"pattern": ".*\\.license$"},
    {"pattern": ".*\\.frag$"},
    {"pattern": ".*\\.vert$"},
    {"pattern": ".*\\.obj$"},
    {"pattern":"\\QProcessorMetadata.txt\\E"}, ,
    {"pattern":"\\Qres/pdf/rs/[AAA] BBB CCC DDD (EEE) V1.4 2019 09 05.pdf\\E"}
  ]
}
```

There is extra comma after this ` {"pattern":"\\QProcessorMetadata.txt\\E"}`.  I guess there is something wrong when merging the content, especially there is a resource file as named in this one `[AAA] BBB CCC DDD (EEE) V1.4 2019 09 05.pdf`.

The content is generated by tracing agent, there is no manual modification on that, and the json generated by tracing agent is valid, could be something wrong in the maven plugin while merging the resource content?

I am using version `<client.plugin.version>0.1.31</client.plugin.version>`.

**Comment by jperedadnr** [comment]
The `resourcesconfig.json` file is only used by the plugin for `resources`. 

For resource bundles we use the `resourcebundles` files (without json format, just a list of fully qualified names (`com.sun.javafx.tk.quantum.QuantumMessagesBundle` is already included by the plugin).

So I suggest you split your content into those two files.

[This](https://github.com/gluonhq/substrate/blob/00f856fa17fbd97465244d975fb193cace3fbbcd/src/main/java/com/gluonhq/substrate/config/ConfigResolver.java#L174) is where we process the json file. 

Can you check that you don't have an extra blank space at the end of the `pattern` lines?

**Comment by samyc1201** [comment]
@jperedadnr 

Thanks, not aware of this `resourcebundles` because the doc doesn't mention this config. Will use this instead.

I regenerate again using the tracing agent:

```
<plugin>
	<groupId>org.openjfx</groupId>
	<artifactId>javafx-maven-plugin</artifactId>
	<version>0.0.4</version>
	<configuration>
		<mainClass>${mainClassName}</mainClass>
		 <options>
            <option>-agentlib:native-image-agent=no-filter,config-output-dir=agent</option>
        </options>
	</configuration>
</plugin>
```

There is indeed an empty space behind the comma `,`:
```
{
  "resources":[
    {"pattern":"\\QProcessorMetadata.txt\\E"}, 
    {"pattern":"\\Qcom/itextpdf/text/pdf/fonts/Helvetica-Bold.afm\\E"}, 
    {"pattern":"\\Qcom/itextpdf/text/pdf/fonts/Helvetica-BoldOblique.afm\\E"}, 
    {"pattern":"\\Qcom/itextpdf/text/pdf/fonts/Helvetica-Oblique.afm\\E"}, 
    {"pattern":"\\Qcom/itextpdf/text/pdf/fonts/Helvetica.afm\\E"}, 
    {"pattern":"\\Qcom/itextpdf/text/pdf/fonts/glyphlist.txt\\E"}, 
    {"pattern":"\\Qdefault.css\\E"}, 
    {"pattern":"\\Qfreemarker/ext/beans/unsafeMethods.txt\\E"}, 
    {"pattern":"\\Qfreemarker/version.properties\\E"}, 
    {"pattern":"\\Qhellofx/openduke.png\\E"}, 
    {"pattern":"\\Qhellofx/styles.css\\E"}, 

...
```

The [line](https://github.com/gluonhq/substrate/blob/00f856fa17fbd97465244d975fb193cace3fbbcd/src/main/java/com/gluonhq/substrate/config/ConfigResolver.java#L174) you point, looks like it trim the `line` and use `startsWith` to check `true` or `false`, it doesn't look like it returns the `line` String which is actually trimmed. I guess the real logic is in `FileOps.readFileLines`, will check it later on when have time.

**Comment by jperedadnr** [comment]
Right, I've filed an issue to document that missing part.
And you are also right about the trim, it is used for the filter, but not for the returned line. Trimming it will remove the leading indentation, so we probably just need to trim it when checking `r.endsWith(",")`.

**Comment by jperedadnr** [comment]
https://github.com/gluonhq/substrate/pull/763 should fix it. You can try the plugin 0.1.32-SNAPSHOT, adding this to your pom: 

```
<pluginRepositories>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by samyc1201** [comment]
I guess 0.1.32-snapshot require extra configuration? I got the error below during native-image compilation, pretty sure my entry point `hellofx.HelloFX` is there:

```
[Mon Aug 31 09:52:20 SGT 2020][FINE] PB Command for compile: /Users/incomemac/Downloads/graalvm-ce-java11-20.2.0-dev/Contents/Home/bin/native-image -Djdk.internal.lambda.eagerlyInitialize=false --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExceptionStackTraces -H:-DeadlockWatchdogExitOnTimeout -H:DeadlockWatchdogInterval=0 -H:+RemoveSaturatedTypeFlows --features=org.graalvm.home.HomeFinderFeature -H:TempDirectory=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/tmp -H:EnableURLProtocols=http,https -H:+PrintAnalysisCallTree -H:Log=registerResource: -H:ReflectionConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/reflectionconfig-arm64-ios.json -H:JNIConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/jniconfig-arm64-ios.json -H:ResourceConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/resourceconfig-arm64-ios.json -H:CompilerBackend=llvm -H:-SpawnIsolates -H:PageSize=16384 -Dsvm.targetName=iOS -Dsvm.targetArch=arm64 -H:+UseCAPCache -H:CAPCacheDir=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/capcache -H:IncludeResourceBundles=com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle,com.sun.media.jfxmedia.MediaErrors,com.sun.webkit.graphics.Images,com.sun.webkit.LocalizedStrings,javafx.scene.web.HTMLEditorSkin -Dsvm.platform=org.graalvm.nativeimage.Platform$DARWIN_AARCH64 -cp /var/folders/qm/8b_c2g1n621b9wp73ymdjwdh0000gn/T/classpathJar2489198726234889578.jar hellofx.HelloFX
[Mon Aug 31 09:52:20 SGT 2020][FINE] Start process compile...
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] [hellofx.hellofx:61937]    classlist:   1,821.51 ms,  0.96 GB
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] Error: Main entry point class 'hellofx.HelloFX' not found.
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Main entry point class 'hellofx.HelloFX' not found.
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:292)
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
[Mon Aug 31 09:52:22 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
[Mon Aug 31 09:52:23 SGT 2020][INFO] [SUB] Error: Image build request failed with exit status 1

```

**Comment by jperedadnr** [comment]
See the command line for compile, it shows
```
-H:TempDirectory=/Users/incomemac/Desktop/income-workplace/HelloFX webview/target/client/arm64-ios/gvm/tmp
```
The blank space is not supported without quotes or a backslash.

Can you rename your project?

**Comment by samyc1201** [comment]
@jperedadnr 

alright, rename the project works. That is weird, it is working in `0.1.31` version even there is space in project name.

**Comment by jperedadnr** [comment]
Maybe it is related to this change: https://github.com/gluonhq/substrate/pull/739, I will investigate.
