### ISSUE TITLE
Grey and empty window after starting application

### ISSUE THREAD

**Issue by moritzluedtke** [gluonhq/client-maven-plugin#271]
## My system
- Mac 10.15.7
- Project: https://github.com/moritzluedtke/folder-wizard
- Java 11
- graalvm-ce-java11-darwin-amd64-20.2.0

## Problem
The build `mvn clean client:build` runs fine. When I double click the application file a terminal opens with no errors and the application window is just grey and shows nothing.

However the application runs fine in IntelliJ (`clean:clean compiler:compile javafx:run -f pom.xml`).

<img width="1238" alt="Bildschirmfoto 2020-10-16 um 14 21 21" src="https://user-images.githubusercontent.com/52150625/96257598-ec6f8f80-0fba-11eb-8c7a-e75bceab2658.png">

**Comment by mipastgt** [comment]
The first thing you should do is check what the output of a `mvn client:run` is.

**Comment by moritzluedtke** [comment]
When there is no build application in the target folder, the output is as follows:
```
java.io.IOException: Application not found at path /Users/mluedtke/Workspace/folder-wizard/target/client/x86_64-darwin/folderwizard
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.runUntilEnd(AbstractTargetConfiguration.java:280)
        at com.gluonhq.substrate.SubstrateDispatcher.nativeRun(SubstrateDispatcher.java:484)
        at com.gluonhq.NativeRunMojo.execute(NativeRunMojo.java:45)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[...]
```

I can post the full output if it's necessary.

When I do build the application first, the output of `mvn client:run`is:
```shell-script
~/Workspace/folder-wizard % mvn client:run
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< de.moritzluedtke:folderwizard >--------------------
[INFO] Building folderwizard 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.28:run (default-cli) @ folderwizard ---
[Mo. Okt. 19 15:31:11 MESZ 2020][INFO] ==================== RUN TASK ====================

// I closed the window right here //

             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.409 s
[INFO] Finished at: 2020-10-19T15:31:23+02:00
[INFO] ------------------------------------------------------------------------
```

The application is still grey as in the screenshot above.

**Comment by jperedadnr** [comment]
You have a _very old_ plugin (0.1.28), bump it to 0.1.33 and try again

**Comment by moritzluedtke** [comment]
My bad. While trying to get it working on my own I also tried using an older version of the plugin and never reverted it.

I did try it again and got nearly the same result. Only difference is one additional log line:
```
~/Workspace/folder-wizard % mvn client:run                                                                                                                                                                                                     (master) in folder-wizard
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< de.moritzluedtke:folderwizard >--------------------
[INFO] Building folderwizard 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.33:run (default-cli) @ folderwizard ---
[Mo. Okt. 19 17:24:29 MESZ 2020][INFO] ==================== RUN TASK ====================
[Mo. Okt. 19 17:24:30 MESZ 2020][INFO] [SUB] 2020-10-19 17:24:30.597 folderwizard[15855:598402] Starting Gluon VM...
// The one line above is new //
            _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.120 s
[INFO] Finished at: 2020-10-19T17:24:40+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by moritzluedtke** [comment]
Good point! I did just that and here is the stack trace:
```
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB] javafx.fxml.LoadException: 
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB] gui/layout/MainWindow.fxml:10
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB] 
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2629)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:930)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:980)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:227)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:752)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2726)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2556)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2470)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3241)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3198)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3167)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3140)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3117)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3110)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at de.moritzluedtke.folderwizard.Starter.createMainWindowGUI(Starter.java:59)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at de.moritzluedtke.folderwizard.Starter.start(Starter.java:39)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at java.security.AccessController.doPrivileged(AccessController.java:101)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB] Caused by: java.lang.ClassNotFoundException: de.moritzluedtke.folderwizard.gui.MainWindowController
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at java.lang.ClassLoader.loadClass(ClassLoader.java:233)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:928)
[Di. Okt. 20 10:20:49 MESZ 2020][INFO] [SUB]    ... 21 more
```

I looked at my FXML file at line 10 but there was nothing wrong in my eyes. It reads like the application does not find the controller class from the FXML file, although the definition is on line 9 and not 10 as the first line in the log suggests. But that might be due to formatting. I tried defining that class without the packages but the results were the same.

Also when I run the same project with `mvn clean compile javafx:run` it works. So I hope my code is not too far off the right way 😅

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_hellofxml_sample, you need to add your controller to the reflectionList. Also for every CNFE you get, you should do the same. GraalVM needs to know in advance what classes are used reflectively, and FXML does use reflection for every class/method found in an fxml file. The plugin already takes care of _most_ of the JavaFX classes, but not all, so you will have to run probably a few iterations.

**Comment by moritzluedtke** [comment]
Wow, you are very fast. Thanks so much for your help! I will give this a try.
