### ISSUE TITLE
Error compiling: Graphics Device initialization failed for :  es2, sw

### ISSUE THREAD

**Issue by taranion** [gluonhq/client-maven-plugin#272]
Hi,

Since yesterday I am running into a compile problem that keeps appearing and vanishing, but I don't know what triggers it,
I had an application which compiled just fine. Than I made changes to a GUI toolkit library (commented out code), recompiled that artifact and recompiled my main application (with client-maven-plugin).

Now I get:
```
[Mo. Okt. 19 10:07:21 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormain:27896]    classlist:   4.449,26 ms,  0,94 GB
[Mo. Okt. 19 10:07:23 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormain:27896]        (cap):     569,21 ms,  0,94 GB
[Mo. Okt. 19 10:07:24 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormain:27896]        setup:   2.102,70 ms,  0,94 GB
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] Graphics Device initialization failed for :  es2, sw
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.perf.PerformanceTracker.logEvent(PerformanceTracker.java:100)
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at javafx.scene.Node.<clinit>(Node.java:408)
...
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 10:07:35 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
```
I reverted the changes and recompiled the library artifact again, but the problem remains.
```
<javafx.plugin.version>0.0.5</javafx.plugin.version>
<client.plugin.version>0.1.33</client.plugin.version>
<javafx.version>15</javafx.version>
GraalVM: 20.2.0
```
The command line was
```
Command Line
============
/opt/graalvm-ce-java11-20.2.0/bin/native-image -Djdk.internal.lambda.eagerlyInitialize=false --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExceptionStackTraces -H:-DeadlockWatchdogExitOnTimeout -H:DeadlockWatchdogInterval=0 -H:+RemoveSaturatedTypeFlows --features=org.graalvm.home.HomeFinderFeature -H:TempDirectory=/home/prelle/git/Mondtor/target/client/x86_64-linux/gvm/tmp -H:EnableURLProtocols=http,https -H:ReflectionConfigurationFiles=/home/prelle/git/Mondtor/target/client/x86_64-linux/gvm/reflectionconfig-x86_64-linux.json -H:JNIConfigurationFiles=/home/prelle/git/Mondtor/target/client/x86_64-linux/gvm/jniconfig-x86_64-linux.json -H:ResourceConfigurationFiles=/home/prelle/git/Mondtor/target/client/x86_64-linux/gvm/resourceconfig-x86_64-linux.json -H:IncludeResourceBundles=de.rpgframework.splittermond.mondtor.FilteredListPage,de.rpgframework.splittermond.mondtor.LibraryPage,de.rpgframework.splittermond.mondtor.LoginDialog,de.rpgframework.splittermond.mondtor.MainScreen,de.rpgframework.splittermond.mondtor.MondtorMain,org.prelle.javafx.JavaFXConstants,org.prelle.rpgframework.jfx.pages.CharactersOverviewPage,org.prelle.rpgframework.splittermond.data.core.i18n.core,org.prelle.splimo.i18n.core,org.prelle.splimo.i18n.core-help,org.prelle.splittermond.chargen.jfx.creatures.LifeformPane,org.prelle.splittermond.chargen.jfx.AttributesPage,org.prelle.splittermond.chargen.jfx.CharacterOverview,org.prelle.splittermond.chargen.jfx.wizard.WizardPageAttributes,org.prelle.splittermond.chargen.jfx.wizard.WizardPageRace,logging,com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle -Dsvm.platform=org.graalvm.nativeimage.Platform$LINUX_AMD64 -cp /tmp/classpathJar11405508149806015483.jar -Duser.language=de -Duser.country=DE de.rpgframework.splittermond.mondtor.MondtorMain
```

I assume that this isn't really related to my hardware setup, since it also fails on Github Actions (where it worked before). The maven-client-plugin and GraalVM 20.2.0 worked for me for some weeks before, so it must be something in my code.

I have no idea what I may have done in my Java code to cause that error. Any ideas?

**Comment by jperedadnr** [comment]
Does a regular [HelloFX sample](https://github.com/gluonhq/gluon-samples/tree/master/HelloFX) still works for you?

**Comment by taranion** [comment]
Tested it. Yes, the example still works. My application still doesn't.

**Comment by jperedadnr** [comment]
Okay, good. Then it's up to you to find out what recent change have you made that breaks the app.

You can also try adding this System properties to your main: `prism.verbose` (true) and `javafx.verbose` (true), build and run again and see if the stacktrace show some indication of the possible error.

**Comment by taranion** [comment]
I noticed that when I make the reflectionconfig.json and resourceconfig.json unavailable, the application compiles.
Of course it won't without these information, but I guess the problem is somehow related to one of the classes listed in the reflectionconfig.json

**Comment by taranion** [comment]
Adding properties to my main wont help, as it fails to compile. Or is there a way to debug GraalVM here?

Is there a way to see **which** class is processed during analysis, when this happens?
``` 
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] Graphics Device initialization failed for :  es2, sw
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.perf.PerformanceTracker.logEvent(PerformanceTracker.java:100)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at javafx.scene.Node.<clinit>(Node.java:408)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:155)
[Mo. Okt. 19 11:43:22 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:419)
```

**Comment by jperedadnr** [comment]
Add `<verbose>true</verbose>` to your pom, that will add `"-H:+PrintAnalysisCallTree"` and `"-H:Log=registerResource:"` flags, so you can see in `target/x86_64/linux/client/gvm` more information.

About properties, doesn't this work for you?

```
public static void main(String[] args) {
        System.setProperty("prism.verbose", "true");
        System.setProperty("javafx.verbose", "true");
        launch(args);
    }
```

**Comment by taranion** [comment]
Thanks for the hint about the additional logs. I got them now, but I don't consider them very helpful. I see my applications main method/class there, but that is the only thing of my code that appears there.

As for the properties, I am well aware how to set them. But the problem does not occur when I tun the code from my IDE, only when I try to compile it with the maven-client-plugin. And since the problem already happens during compilation, setting the properties isn't of much use.

I will try to exclude code and my 100 reflection classes now, until I get to the point where compilation does work again.

**Comment by jperedadnr** [comment]
Hm, your error is at runtime, but then you say "it doesn't compile" ?? Then what exception do you get?

**Comment by taranion** [comment]
I don't understand the runtime thing either.

My error occurs when I am doing **mvn client:compile client:link**

```
bash-5.0$ mvn clean client:compile client:link 
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< de.rpgframework.splittermond:mondtor >----------------
[INFO] Building Mondtor 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mondtor ---
[INFO] Deleting /home/prelle/git/Mondtor/target
[INFO] 
[INFO] >>> client-maven-plugin:0.1.33:compile (default-cli) > process-classes @ mondtor >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mondtor ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 33 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ mondtor ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to /home/prelle/git/Mondtor/target/classes
[INFO] 
[INFO] <<< client-maven-plugin:0.1.33:compile (default-cli) < process-classes @ mondtor <<<
[INFO] 
[INFO] 
[INFO] --- client-maven-plugin:0.1.33:compile (default-cli) @ mondtor ---
[Mo. Okt. 19 13:57:42 MESZ 2020][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Mo. Okt. 19 13:57:48 MESZ 2020][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.
[Mo. Okt. 19 13:57:48 MESZ 2020][INFO] Logging process [objdump] to file: /home/prelle/git/Mondtor/target/client/log/process-objdump-1603108668793.log
[Mo. Okt. 19 13:57:48 MESZ 2020][INFO] Logging process [objdump] to file: /home/prelle/git/Mondtor/target/client/log/process-objdump-1603108668843.log
[Mo. Okt. 19 13:57:53 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormainmini:40712]    classlist:   3.307,83 ms,  0,96 GB
[Mo. Okt. 19 13:57:54 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormainmini:40712]        (cap):     600,06 ms,  0,96 GB
[Mo. Okt. 19 13:57:55 MESZ 2020][INFO] [SUB] [de.rpgframework.splittermond.mondtor.mondtormainmini:40712]        setup:   2.236,86 ms,  0,96 GB
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] Graphics Device initialization failed for :  es2, sw
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.sun.javafx.perf.PerformanceTracker.logEvent(PerformanceTracker.java:100)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at javafx.scene.Node.<clinit>(Node.java:408)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:155)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:419)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:407)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:384)
[Mo. Okt. 19 13:58:12 MESZ 2020][INFO] [SUB] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:76)
```

**Comment by jperedadnr** [comment]
Since you initially posted a `java.lang.RuntimeException` I thought it was during `mvn client:run`...
Now I see that it happens during the compilation phase, which shouldn't happen at all...

I see from your statcktrace, that during analysis there is a call to `PerformanceTracker.logEvent("Node class loaded");`, which seems to initialize the QuantumRender. That shouldn't happen...

Are you enabling the `PerformanceTracker`?

**Comment by taranion** [comment]
No. In fact I wasn't aware of the `PerformanceTracker` until you now mentioned it.

**Comment by taranion** [comment]
My current plugin configuration is
```
<plugin>
	<groupId>com.gluonhq</groupId>
	<artifactId>client-maven-plugin</artifactId>
	<version>${client.plugin.version}</version>
	<configuration>
		<bundlesList>
			<list>de.rpgframework.splittermond.mondtor.FilteredListPage</list>
			<list>de.rpgframework.splittermond.mondtor.LibraryPage</list>
			<list>de.rpgframework.splittermond.mondtor.LoginDialog</list>
			<list>de.rpgframework.splittermond.mondtor.MainScreen</list>
			<list>de.rpgframework.splittermond.mondtor.MondtorMain</list>
			<list>org.prelle.javafx.JavaFXConstants</list>
			<list>org.prelle.rpgframework.jfx.pages.CharactersOverviewPage</list>
			<list>org.prelle.rpgframework.splittermond.data.core.i18n.core</list>
			<list>org.prelle.splimo.i18n.core</list>
			<list>org.prelle.splimo.i18n.core-help</list>
			<list>org.prelle.splittermond.chargen.jfx.creatures.LifeformPane</list>
			<list>org.prelle.splittermond.chargen.jfx.AttributesPage</list>
			<list>org.prelle.splittermond.chargen.jfx.CharacterOverview</list>
			<list>org.prelle.splittermond.chargen.jfx.wizard.WizardPageAttributes</list>
			<list>org.prelle.splittermond.chargen.jfx.wizard.WizardPageRace</list>
			<list>logging</list>
		</bundlesList>
		<mainClass>${mainClassName}</mainClass>
		<nativeImageArgs>
			<arg>-Duser.language=de</arg>
			<arg>-Duser.country=DE</arg>
			<arg>-H:+PrintAnalysisCallTree</arg>
			<arg>-H:Log=registerResource:</arg>
		</nativeImageArgs>
		<attachList>
			<list>browser</list>
			<list>connectivity</list>
			<list>device</list>
			<list>display</list>
			<list>lifecycle</list>
			<list>orientation</list>
			<list>settings</list>
			<list>statusbar</list>
			<list>storage</list>
		</attachList>
	</configuration>
</plugin>
```

**Comment by jperedadnr** [comment]
In theory, the tracker is enabled from `perfLog = systemProperties.getProperty("sun.perflog");` in PrismSettings. Maybe you have a dependency that sets that property?? 
Can you print `System.getProperties()` in your main, and run it with `mvn javafx:run` and see if you can find something related?

**Comment by taranion** [comment]
Well, now it gets funny. I cannot reproduce the problem anymore. 
I did recompile my library with custom UI controls for the Xth time today and suddenly the main application compiles without error. Thanks to Git, I reverted everything - library and app - to the state where I started working today (when the error was still present) and was able to recompile everything without problems!

So, it is working for now - but I am not any wiser than before. 

Here are the properties when running the binary
```
file.encoding  	= UTF-8
file.separator  	= /
java.class.path  	= 
java.class.version  	= 55.0
java.endorsed.dirs  	= 
java.ext.dirs  	= 
java.io.tmpdir  	= /tmp
java.library.path  	= 
java.specification.name  	= Java Platform API Specification
java.specification.vendor  	= Oracle Corporation
java.specification.version  	= 11
java.vendor  	= Oracle Corporation
java.vendor.url  	= https://www.graalvm.org/
java.version  	= 11.0.8
java.vm.name  	= Substrate VM
java.vm.specification.name  	= Java Virtual Machine Specification
java.vm.specification.vendor  	= Oracle Corporation
java.vm.specification.version  	= 11
java.vm.vendor  	= Oracle Corporation
java.vm.version  	= GraalVM 20.2.0 Java 11
jdk.lang.Process.launchMechanism  	= FORK
line.separator  	= 

org.graalvm.nativeimage.imagecode  	= runtime
org.graalvm.nativeimage.kind  	= shared
os.arch  	= amd64
os.name  	= Linux
os.version  	= 5.8.14-200.fc32.x86_64
path.separator  	= :
sun.arch.data.model  	= 64
sun.jnu.encoding  	= UTF-8
user.dir  	= /home/prelle/git/Mondtor
user.home  	= /home/prelle
user.name  	= prelle
```
and those are the properties running from within `mvn javafx:run`
```
agentscript.home  	= /opt/graalvm-ce-java11-20.2.0/tools/agentscript
awt.toolkit  	= sun.awt.X11.XToolkit
chromeinspector.home  	= /opt/graalvm-ce-java11-20.2.0/tools/chromeinspector
coverage.home  	= /opt/graalvm-ce-java11-20.2.0/tools/coverage
file.encoding  	= UTF-8
file.separator  	= /
java.awt.graphicsenv  	= sun.awt.X11GraphicsEnvironment
java.awt.printerjob  	= sun.print.PSPrinterJob
java.class.path  	= /home/prelle/git/Mondtor/target/classes:/home/prelle/.m2/repository/com/gluonhq/attach/browser/4.0.8/browser-4.0.8.jar:/home/prelle/.m2/repository/com/gluonhq/attach/connectivity/4.0.8/connectivity-4.0.8.jar:/home/prelle/.m2/repository/com/gluonhq/attach/device/4.0.8/device-4.0.8.jar:/home/prelle/.m2/repository/com/gluonhq/attach/orientation/4.0.8/orientation-4.0.8.jar:/home/prelle/.m2/repository/com/gluonhq/attach/statusbar/4.0.8/statusbar-4.0.8.jar:/home/prelle/.m2/repository/com/gluonhq/attach/storage/4.0.8/storage-4.0.8-desktop.jar:/home/prelle/.m2/repository/com/gluonhq/attach/storage/4.0.8/storage-4.0.8.jar:/home/prelle/.m2/repository/com/paypal/paypalhttp/1.0.0/paypalhttp-1.0.0.jar:/home/prelle/.m2/repository/com/paypal/sdk/checkout-sdk/1.0.2/checkout-sdk-1.0.2.jar:/home/prelle/.m2/repository/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar:/home/prelle/.m2/repository/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar:/home/prelle/.m2/repository/de/rpgframework/eden-backend/0.0.1-SNAPSHOT/eden-backend-0.0.1-SNAPSHOT.jar:/home/prelle/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/prelle/.m2/repository/junit/junit/5.0-SNAPSHOT/junit-5.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/apache/logging/log4j/log4j-core/2.13.3/log4j-core-2.13.3.jar:/home/prelle/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/prelle/.m2/repository/org/openjfx/javafx-base/15/javafx-base-15.jar:/home/prelle/.m2/repository/org/openjfx/javafx-controls/15/javafx-controls-15.jar:/home/prelle/.m2/repository/org/openjfx/javafx-fxml/15/javafx-fxml-15.jar:/home/prelle/.m2/repository/org/openjfx/javafx-graphics/15/javafx-graphics-15.jar:/home/prelle/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar:/home/prelle/.m2/repository/org/slf4j/slf4j-jdk14/2.0.0-alpha1/slf4j-jdk14-2.0.0-alpha1.jar
java.class.version  	= 55.0
java.home  	= /opt/graalvm-ce-java11-20.2.0
java.io.tmpdir  	= /tmp
java.library.path  	= /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.runtime.name  	= OpenJDK Runtime Environment
java.runtime.version  	= 11.0.8+10-jvmci-20.2-b03
java.specification.name  	= Java Platform API Specification
java.specification.vendor  	= Oracle Corporation
java.specification.version  	= 11
java.vendor  	= GraalVM Community
java.vendor.url  	= https://www.graalvm.org/
java.vendor.url.bug  	= https://github.com/oracle/graal/issues
java.vendor.version  	= GraalVM CE 20.2.0
java.version  	= 11.0.8
java.version.date  	= 2020-07-14
java.vm.compressedOopsMode  	= Zero based
java.vm.info  	= mixed mode, sharing
java.vm.name  	= OpenJDK 64-Bit Server VM
java.vm.specification.name  	= Java Virtual Machine Specification
java.vm.specification.vendor  	= Oracle Corporation
java.vm.specification.version  	= 11
java.vm.vendor  	= GraalVM Community
java.vm.version  	= 11.0.8+10-jvmci-20.2-b03
javafx.runtime.version  	= 15+9
javafx.version  	= 15
jdk.debug  	= release
jdk.internal.vm.ci.enabled  	= true
jdk.module.main  	= mondtor
jdk.module.main.class  	= de.rpgframework.splittermond.mondtor.MondtorMain
jdk.module.path  	= /home/prelle/git/Mondtor/target/classes:/home/prelle/.m2/repository/com/gluonhq/attach/display/4.0.8/display-4.0.8-desktop.jar:/home/prelle/.m2/repository/com/gluonhq/attach/lifecycle/4.0.8/lifecycle-4.0.8-desktop.jar:/home/prelle/.m2/repository/com/gluonhq/attach/settings/4.0.8/settings-4.0.8-desktop.jar:/home/prelle/.m2/repository/com/gluonhq/attach/util/4.0.8/util-4.0.8.jar:/home/prelle/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/home/prelle/.m2/repository/de/rpgframework/eden-client/0.0.1-SNAPSHOT/eden-client-0.0.1-SNAPSHOT.jar:/home/prelle/.m2/repository/de/rpgframework/rpgframework-core/5.0.0-SNAPSHOT/rpgframework-core-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/de/rpgframework/rpgframework-javafx/5.0.0-SNAPSHOT/rpgframework-javafx-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/de/rpgframework/rpgframework-rules/5.0.0-SNAPSHOT/rpgframework-rules-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar:/home/prelle/.m2/repository/org/openjfx/javafx-base/15/javafx-base-15-linux.jar:/home/prelle/.m2/repository/org/openjfx/javafx-controls/15/javafx-controls-15-linux.jar:/home/prelle/.m2/repository/org/openjfx/javafx-fxml/15/javafx-fxml-15-linux.jar:/home/prelle/.m2/repository/org/openjfx/javafx-graphics/15/javafx-graphics-15-linux.jar:/home/prelle/.m2/repository/org/prelle/javafx-extensions/5.0.0-SNAPSHOT/javafx-extensions-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/prelle/simple-persist/3.2.0-SNAPSHOT/simple-persist-3.2.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/prelle/splittermond-chargen/5.0.0-SNAPSHOT/splittermond-chargen-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/prelle/splittermond-chargen-jfx/5.0.0-SNAPSHOT/splittermond-chargen-jfx-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/prelle/splittermond-core/5.0.0-SNAPSHOT/splittermond-core-5.0.0-SNAPSHOT.jar:/home/prelle/.m2/repository/org/prelle/splittermond-data/5.0.0-SNAPSHOT/splittermond-data-5.0.0-SNAPSHOT.jar
js.home  	= /opt/graalvm-ce-java11-20.2.0/languages/js
line.separator  	= 

llvm.home  	= /opt/graalvm-ce-java11-20.2.0/languages/llvm
lsp.home  	= /opt/graalvm-ce-java11-20.2.0/tools/lsp
nfi.home  	= /opt/graalvm-ce-java11-20.2.0/languages/nfi
org.graalvm.home  	= /opt/graalvm-ce-java11-20.2.0
org.graalvm.language.js.home  	= /opt/graalvm-ce-java11-20.2.0/languages/js
org.graalvm.language.llvm.home  	= /opt/graalvm-ce-java11-20.2.0/languages/llvm
org.graalvm.language.nfi.home  	= /opt/graalvm-ce-java11-20.2.0/languages/nfi
org.graalvm.language.regex.home  	= /opt/graalvm-ce-java11-20.2.0/languages/regex
org.graalvm.tool.agentscript.home  	= /opt/graalvm-ce-java11-20.2.0/tools/agentscript
org.graalvm.tool.chromeinspector.home  	= /opt/graalvm-ce-java11-20.2.0/tools/chromeinspector
org.graalvm.tool.coverage.home  	= /opt/graalvm-ce-java11-20.2.0/tools/coverage
org.graalvm.tool.lsp.home  	= /opt/graalvm-ce-java11-20.2.0/tools/lsp
org.graalvm.tool.profiler.home  	= /opt/graalvm-ce-java11-20.2.0/tools/profiler
org.graalvm.version  	= 20.2.0
os.arch  	= amd64
os.name  	= Linux
os.version  	= 5.8.14-200.fc32.x86_64
path.separator  	= :
profiler.home  	= /opt/graalvm-ce-java11-20.2.0/tools/profiler
regex.home  	= /opt/graalvm-ce-java11-20.2.0/languages/regex
sun.arch.data.model  	= 64
sun.boot.library.path  	= /opt/graalvm-ce-java11-20.2.0/lib
sun.cpu.endian  	= little
sun.cpu.isalist  	= 
sun.io.unicode.encoding  	= UnicodeLittle
sun.java.command  	= mondtor/de.rpgframework.splittermond.mondtor.MondtorMain
sun.java.launcher  	= SUN_STANDARD
sun.jnu.encoding  	= UTF-8
sun.management.compiler  	= HotSpot 64-Bit Tiered Compilers
sun.os.patch.level  	= unknown
user.country  	= DE
user.dir  	= /home/prelle/git/Mondtor
user.home  	= /home/prelle
user.language  	= de
user.name  	= prelle
user.timezone  	= Europe/Berlin
```

I don't know where to go from here? Shall we close this ticket? Shall we keep it open some more days (since this is the second time I ran into this error and it vanished again without me having made relevant changes)?

**Comment by jperedadnr** [comment]
Interesting...

If you run without a display (i.e. from GitHub actions), probably it is wise to enable the `sw` pipeline, by adding:

```
<enableSWRendering>true</enableSWRendering>
```
to the Client plugin.

**Comment by jperedadnr** [comment]
We can close this now, feel free to reopen in the problem happens again.
