### ISSUE TITLE
No language and polyglot implementation was found on the classpath

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/client-maven-plugin#285]
dependency :
```
       <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>20.3.0</version>
        </dependency>
```
code : 
```
    public static void main(String[] args) {
        Context polyglot = Context.create();
        Value array = polyglot.eval("js", "[1,2,42,4]");
        System.out.println(array.getArrayElement(2).asInt());
    }
```
It runs  normally in IDEA。Console output：
···
42
···
but when i run ·mvn clean client:build client:run·, that threw an exception : 
```
Exception in thread "main" java.lang.IllegalStateException: No language and polyglot implementation was found on the classpath. Make sure a language is added to the classpath (e.g., native-image --language:js).
     at org.graalvm.polyglot.Engine$PolyglotInvalid.noPolyglotImplementationFound(Engine.java:860)
     at org.graalvm.polyglot.Engine$PolyglotInvalid.buildEngine(Engine.java:781)
     at org.graalvm.polyglot.Engine$Builder.build(Engine.java:530)
     at org.graalvm.polyglot.Context$Builder.build(Context.java:1587)
     at org.graalvm.polyglot.Context.create(Context.java:808)
     at graalvm.Test.main(Test.java:11)
```
Did I miss anything？

**Comment by EvokeAngle** [comment]
I solved this by add something：
```
<nativeImageArg>--language:js</nativeImageArg>
```

**Comment by zsuiqiang** [comment]
add where?
