### ISSUE TITLE
MissingResourceException on mvn client:run goal when XPath is being evaluated

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [gluonhq/client-maven-plugin#297]
In my JavaFX app I am parsing some values from XML file using XPath queries.
This app works fine when run in IDE and it is even built correctly as native Windows image.
However, when the final exe is executed, nothing shows. When executed from commandline, I can see stacktrace with the `MissingResourceException` coming from line when XPath is evaluated:
```
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB] Exception in Application start method
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at java.lang.Thread.run(Thread.java:834)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB] Caused by: java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xml.internal.res.XMLErrorResources
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at jdk.xml.internal.SecuritySupport.lambda$getResourceBundle$5(SecuritySupport.java:274)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:84)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at jdk.xml.internal.SecuritySupport.getResourceBundle(SecuritySupport.java:267)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at jdk.xml.internal.SecuritySupport.getResourceBundle(SecuritySupport.java:257)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xml.internal.res.XMLMessages.createXMLMessage(XMLMessages.java:84)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xml.internal.utils.ObjectPool.getInstance(ObjectPool.java:144)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xml.internal.utils.StringBufferPool.get(StringBufferPool.java:45)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getStringValue(DOM2DTM.java:822)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xpath.internal.objects.XNodeSet.getStringFromNode(XNodeSet.java:219)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xpath.internal.objects.XNodeSet.str(XNodeSet.java:282)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xpath.internal.jaxp.XPathImplUtil.getResultAsType(XPathImplUtil.java:147)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:182)
[Tue Feb 09 08:40:07 CET 2021][INFO] [SUB]      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:196)
```
In my `module-info.java` I have `requires java.xml;`.
Not sure what else should be set to avoid this error.

graalvm-ce-java11-21.0.0

```xml
<maven.compiler.release>11</maven.compiler.release>
<javafx.version>15.0.1</javafx.version>
<attach.version>4.0.10</attach.version>
<client.plugin.version>0.1.36</client.plugin.version>
<javafx.plugin.version>0.0.5</javafx.plugin.version>
```

**Comment by jan-tosovsky-cz** [comment]
Adding that class into the bundleList in the plugin `<configuration>` section and rebuilding the native image did the trick.
```xml
<bundlesList>
    <list>com.sun.org.apache.xml.internal.res.XMLErrorResources</list>
</bundlesList>
```

**Comment by jperedadnr** [comment]
Yes, that is the correct approach, as documented here: https://docs.gluonhq.com/#_bundleslist
