### ISSUE TITLE
Using On Screen Keyboard throws Null Pointer

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/client-maven-plugin#317]
Hi, using the following runtime arguments : 
`-Dcom.sun.javafx.touch=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dcom.sun.javafx.isEmbedded=true ` while running native image, and then clicking on the text fields give this error:

```
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:167)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:93)
        at com.sun.javafx.scene.control.skin.FXVKSkin.loadBoard(FXVKSkin.java:1014)
        at com.sun.javafx.scene.control.skin.FXVKSkin.rebuildPrimaryVK(FXVKSkin.java:612)
        at com.sun.javafx.scene.control.skin.FXVKSkin.updateKeyboardType(FXVKSkin.java:373)
        at com.sun.javafx.scene.control.skin.FXVKSkin$1.invalidated(FXVKSkin.java:505)
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:78)
        at com.sun.javafx.scene.control.skin.FXVK.setAttachedNode(FXVK.java:84)
        at com.sun.javafx.scene.control.skin.FXVK.attach(FXVK.java:102)
        at javafx.scene.control.skin.TextInputControlSkin.lambda$new$1(TextInputControlSkin.java:286)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
        at javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8124)
        at javafx.scene.Scene$12.invalidated(Scene.java:2166)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.scene.Scene$KeyHandler.setFocusOwner(Scene.java:4029)
        at javafx.scene.Scene$KeyHandler.requestFocus(Scene.java:4076)
        at javafx.scene.Scene.requestFocus(Scene.java:2130)
        at javafx.scene.Node.requestFocus(Node.java:8285)
        at com.sun.javafx.scene.control.behavior.TextFieldBehavior.mousePressed(TextFieldBehavior.java:224)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3861)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1854)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2587)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
        at java.security.AccessController.doPrivileged(AccessController.java:100)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:413)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
        at com.sun.glass.ui.View.notifyMouse(View.java:942)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

**Comment by tiainen** [comment]
You are the first to actually test the virtual keyboard code. You'll need to add the keyboard layout text files to your `resourceconfig.json` in `src/main/resources/META-INF/substrate/config/` as described in https://docs.gluonhq.com/#_resources. In this case you can easily copy the sample `resourceconfig.json` file that is provided in the documentation, since the layout files are four txt files: https://github.com/openjdk/jfx/tree/master/modules/javafx.controls/src/main/resources/com/sun/javafx/scene/control/skin

We might want to add these 4 files by default when building a JavaFX native image.

**Comment by rnayabed** [comment]
@tiainen Thank you! It works! 

here is my `resource-config.json`:

```
{
  "resources": [
    {"pattern": ".*/Default.zip$"},
    {"pattern": ".*/(EmailBoard|NumericBoard|TextBoard|UriBoard).txt$"}
  ]
}
```
