### ISSUE TITLE
Runtime NPE for Locale other than the one specified in compile script 

### ISSUE THREAD

**Issue by maxum2610** [gluonhq/client-maven-plugin#43]
A Nullpointer Exception is thrown when trying to retrieve Locale specific information at runtime, in this case DecimalFormatSymbols.

The default values in compile.sh for -Duser.country and -Duser.language are set to US and en.
Retrieving Locale specific information for any Locale other than Locale.ENGLISH will throw a nullpointer exception. Changing -Duser.country and -Duser.language to the desired locale values allows the code to pass. The plugin user should be able to set these value in maven/gradle. Not sure if there's a workaround for apps that need multilingual support.

OSX 10.14.5 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

mvn client:run
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< be.digitalsolutions:maventestproject >----------------
[INFO] Building maventestproject 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.0.11:run (default-cli) @ maventestproject ---
Omega :: host triplet = x86_64-macos-macos
Omega :: target triplet = x86_64-macos-macos
[Wed Aug 21 16:52:51 CEST 2019][FINE] ==================== RUN TASK ====================
[Wed Aug 21 16:52:51 CEST 2019][FINE] Running at /Users/brunoposthuma/WORK/ACSY/maventestproject/target/client
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Hello, JAVA main, argc = 1, argv = 0x7ffee2ee5fb0
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 2019-08-21 16:52:51.300 maventestproject[48715:2394354] Starting Gluon VM...
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Starting Hello
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Trying for Locale.forLanguageTag("nl-BE")
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Error for Locale.forLanguageTag("nl-BE")
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] java.lang.NullPointerException
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at jdk.internal.loader.BootLoader.hasClassPath(BootLoader.java:101)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1189)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:255)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:253)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:252)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:160)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.of(Bundles.java:106)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:177)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.<init>(Hello.java:48)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.main(Hello.java:94)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Trying for new Locale("nl", "BE")
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] OK for new Locale("nl-BE")
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Error for new Locale("nl-BE")
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] java.lang.NullPointerException
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at jdk.internal.loader.BootLoader.hasClassPath(BootLoader.java:101)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1189)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:255)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:253)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:252)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:160)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.of(Bundles.java:106)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:177)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.<init>(Hello.java:60)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.main(Hello.java:94)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Trying for Locale.FRENCH
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Error for Locale.FRENCH
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] java.lang.NullPointerException
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at jdk.internal.loader.BootLoader.hasClassPath(BootLoader.java:101)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1189)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:255)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:253)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:252)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.of(Bundles.java:106)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:63)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:177)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.<init>(Hello.java:69)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.main(Hello.java:94)
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Trying for Locale.ENGLISH
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] Ok for Locale.ENGLISH
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] By By Hello
[Wed Aug 21 16:52:51 CEST 2019][INFO] [SUB] 2019-08-21 16:52:51.310 maventestproject[48715:2394354] Started Gluon VM...

Hello.java:

package be.digitalsolutions.maventestproject;

import java.text.DecimalFormatSymbols;
import java.util.Locale;

public class Hello
{

     public Hello() 
    {
        
        System.out.println("Starting Hello");
        

        /* Causes NPE in jdk.internal.loader.BootLoader because jdk.internal.loader.ClassLoaders.BOOT_LOADER is not
           initialized.
        
        static {
        
        //-Xbootclasspath/a or -javaagent with Boot-Class-Path attribute
        String append = jdk.internal.misc.VM.getSavedProperty("jdk.boot.class.path.append");
        BOOT_LOADER =
            new jdk.internal.loader.ClassLoaders.BootClassLoader((append != null && append.length() > 0)
                ? new jdk.internal.loader.URLClassPath(append, true)
                : null);
        
        ...
        }
        
        Note: shouldn't even get here:
        
        java.util.ServiceLoader forks to $LazyClassPathLookupIterator instead 
        of $ModuleServicesLookupIterator in function:
        private Iterator<Provider<S>> newLookupIterator() {}
        */
        // set -Duser.country=BE and -Duser.language=nl in config.sh and this passes
        try {
            System.out.println("Trying for Locale.forLanguageTag(\"nl-BE\")");
            Locale beNl = Locale.forLanguageTag("nl-BE");
            DecimalFormatSymbols.getInstance(beNl);
            System.out.println("Ok for Locale.forLanguageTag(\"nl-BE\")");
        } catch(Exception e) {
            System.out.println("Error for Locale.forLanguageTag(\"nl-BE\")");
            e.printStackTrace();
        }

        // set -Duser.country=BE and -Duser.language=nl in config.sh and this passes
        try {
            System.out.println("Trying for new Locale(\"nl\", \"BE\")");
            Locale beNl = new Locale("nl","BE");
            System.out.println("OK for new Locale(\"nl-BE\")");
            DecimalFormatSymbols.getInstance(beNl);
        } catch(Exception e) {
            System.out.println("Error for new Locale(\"nl-BE\")");
            e.printStackTrace();
        }
        
        // set -Duser.country=FR and -Duser.language=fr in config.sh and this passes
        try {
            System.out.println("Trying for Locale.FRENCH");
            DecimalFormatSymbols.getInstance(Locale.FRENCH);
            System.out.println("Ok for Locale.FRENCH");
        } catch(Exception e) {
            System.out.println("Error for Locale.FRENCH");
            e.printStackTrace();
        }
                
        // this always works => hard coded in JDK
        try {
            System.out.println("Trying for Locale.ENGLISH");
            DecimalFormatSymbols.getInstance(Locale.ENGLISH);
            System.out.println("Ok for Locale.ENGLISH");
        } catch(Exception e) {
            System.out.println("Error for Locale.ENGLISH");
            e.printStackTrace();
        }
                
        // Same error on jdbc getConnection
        
        System.out.println("By By Hello");
 
    }
    
    public static void main(String[] args) {
        new Hello();
    }
}

module-info.java:

module Maventestproject {
    requires java.base;
}

pom.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>be.digitalsolutions</groupId>
    <artifactId>maventestproject</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <mainClassName>Maventestproject/be.digitalsolutions.maventestproject.Hello</mainClassName>
        <mainClass>be.digitalsolutions.maventestproject.Hello</mainClass>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    
                    <debug>11</debug>
                    <compilerArgs>
                        <arg>-g</arg>
                        <arg>--add-exports</arg>
                        <arg>java.base/jdk.internal.loader=ALL-UNNAMED</arg>
                        <arg>--add-exports</arg>
                        <arg>java.base/jdk.internal.misc=ALL-UNNAMED</arg>
                        <arg>--add-exports</arg>
                        <arg>java.base/jdk.internal.loader=Maventestproject</arg>
                        <arg>--add-exports</arg>
                        <arg>java.base/jdk.internal.misc=Maventestproject</arg>
                        
                        
                                            
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                      <manifest>
                        <addClasspath>true</addClasspath>
                        <mainClass>${mainClass}</mainClass>
                      </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.5.0</version>
                <executions>
                    <execution>
                        
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>${mainClassName}</mainClass>
                        </configuration>
                    </execution>
                    <execution>
                        
                        <id>debug</id>
                        <configuration>
                            <options>
                                <option>--add-opens</option>
                                <option>java.base/jdk.internal.loader=ALL-UNNAMED</option>
                                <option>--add-exports</option>
                                <option>java.base/jdk.internal.loader=ALL-UNNAMED</option>
                                <option>--add-exports</option>
                                <option>java.base/jdk.internal.misc=ALL-UNNAMED</option>
                                
                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:8000</option>
                            </options>
                            <mainClass>${mainClassName}</mainClass>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
             <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>0.0.11</version>
                <configuration>
                    <verbose>true</verbose>
                    <bundlesList>
                    </bundlesList>
                    <jniList>
                        <list>java.util.Locale</list>
                    </jniList>
                    <reflectionList>
                        <list>java.util.Locale</list>
                    </reflectionList>
                    <mainClass>${mainClassName}</mainClass>
                </configuration>
            </plugin>
            
            
            
        </plugins>

    </build>      
    <pluginRepositories>
        <pluginRepository>
            <id>gluon-releases</id>
            <url>http://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </pluginRepository>
    </pluginRepositories>  
</project>

[client-debug0.log](https://github.com/gluonhq/client-maven-plugin/files/3525970/client-debug0.log)

**Comment by maxum2610** [comment]
This is a Graalvm native-image issue.
